# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yb/docdb/docdb.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from yb.common import common_pb2 as yb_dot_common_dot_common__pb2
from yb.util import opid_pb2 as yb_dot_util_dot_opid__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='yb/docdb/docdb.proto',
  package='yb.docdb',
  syntax='proto2',
  serialized_options=b'\n\014org.yb.docdb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14yb/docdb/docdb.proto\x12\x08yb.docdb\x1a\x16yb/common/common.proto\x1a\x12yb/util/opid.proto\"J\n\x0eKeyValuePairPB\x12\x0b\n\x03key\x18\x01 \x01(\x0c\x12\r\n\x05value\x18\x02 \x01(\x0c\x12\x1c\n\x14\x65xternal_hybrid_time\x18\x03 \x01(\x06\"P\n\x1a\x41pplyExternalTransactionPB\x12\x16\n\x0etransaction_id\x18\x01 \x01(\x0c\x12\x1a\n\x12\x63ommit_hybrid_time\x18\x02 \x01(\x06\"\xbc\x02\n\x14KeyValueWriteBatchPB\x12-\n\x0bwrite_pairs\x18\x01 \x03(\x0b\x32\x18.yb.docdb.KeyValuePairPB\x12.\n\x0btransaction\x18\x02 \x01(\x0b\x32\x19.yb.TransactionMetadataPB\x12$\n\x1c\x44\x45PRECATED_may_have_metadata\x18\x03 \x01(\x08\x12,\n\nread_pairs\x18\x05 \x03(\x0b\x32\x18.yb.docdb.KeyValuePairPB\x12&\n\rrow_mark_type\x18\x06 \x01(\x0e\x32\x0f.yb.RowMarkType\x12I\n\x1b\x61pply_external_transactions\x18\x07 \x03(\x0b\x32$.yb.docdb.ApplyExternalTransactionPB\"y\n\x13\x43onsensusFrontierPB\x12\x19\n\x05op_id\x18\x01 \x01(\x0b\x32\n.yb.OpIdPB\x12\x13\n\x0bhybrid_time\x18\x02 \x01(\x06\x12\x16\n\x0ehistory_cutoff\x18\x03 \x01(\x06\x12\x1a\n\x12hybrid_time_filter\x18\x04 \x01(\x06\"K\n\x17\x41pplyTransactionStatePB\x12\x0b\n\x03key\x18\x01 \x01(\x0c\x12\x10\n\x08write_id\x18\x02 \x01(\r\x12\x11\n\tcommit_ht\x18\x03 \x01(\x06\x42\x0e\n\x0corg.yb.docdb'
  ,
  dependencies=[yb_dot_common_dot_common__pb2.DESCRIPTOR,yb_dot_util_dot_opid__pb2.DESCRIPTOR,])




_KEYVALUEPAIRPB = _descriptor.Descriptor(
  name='KeyValuePairPB',
  full_name='yb.docdb.KeyValuePairPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='yb.docdb.KeyValuePairPB.key', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='yb.docdb.KeyValuePairPB.value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='external_hybrid_time', full_name='yb.docdb.KeyValuePairPB.external_hybrid_time', index=2,
      number=3, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=152,
)


_APPLYEXTERNALTRANSACTIONPB = _descriptor.Descriptor(
  name='ApplyExternalTransactionPB',
  full_name='yb.docdb.ApplyExternalTransactionPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='transaction_id', full_name='yb.docdb.ApplyExternalTransactionPB.transaction_id', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='commit_hybrid_time', full_name='yb.docdb.ApplyExternalTransactionPB.commit_hybrid_time', index=1,
      number=2, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=234,
)


_KEYVALUEWRITEBATCHPB = _descriptor.Descriptor(
  name='KeyValueWriteBatchPB',
  full_name='yb.docdb.KeyValueWriteBatchPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='write_pairs', full_name='yb.docdb.KeyValueWriteBatchPB.write_pairs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transaction', full_name='yb.docdb.KeyValueWriteBatchPB.transaction', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='DEPRECATED_may_have_metadata', full_name='yb.docdb.KeyValueWriteBatchPB.DEPRECATED_may_have_metadata', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='read_pairs', full_name='yb.docdb.KeyValueWriteBatchPB.read_pairs', index=3,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='row_mark_type', full_name='yb.docdb.KeyValueWriteBatchPB.row_mark_type', index=4,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='apply_external_transactions', full_name='yb.docdb.KeyValueWriteBatchPB.apply_external_transactions', index=5,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=237,
  serialized_end=553,
)


_CONSENSUSFRONTIERPB = _descriptor.Descriptor(
  name='ConsensusFrontierPB',
  full_name='yb.docdb.ConsensusFrontierPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='op_id', full_name='yb.docdb.ConsensusFrontierPB.op_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hybrid_time', full_name='yb.docdb.ConsensusFrontierPB.hybrid_time', index=1,
      number=2, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='history_cutoff', full_name='yb.docdb.ConsensusFrontierPB.history_cutoff', index=2,
      number=3, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hybrid_time_filter', full_name='yb.docdb.ConsensusFrontierPB.hybrid_time_filter', index=3,
      number=4, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=555,
  serialized_end=676,
)


_APPLYTRANSACTIONSTATEPB = _descriptor.Descriptor(
  name='ApplyTransactionStatePB',
  full_name='yb.docdb.ApplyTransactionStatePB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='yb.docdb.ApplyTransactionStatePB.key', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='write_id', full_name='yb.docdb.ApplyTransactionStatePB.write_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='commit_ht', full_name='yb.docdb.ApplyTransactionStatePB.commit_ht', index=2,
      number=3, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=678,
  serialized_end=753,
)

_KEYVALUEWRITEBATCHPB.fields_by_name['write_pairs'].message_type = _KEYVALUEPAIRPB
_KEYVALUEWRITEBATCHPB.fields_by_name['transaction'].message_type = yb_dot_common_dot_common__pb2._TRANSACTIONMETADATAPB
_KEYVALUEWRITEBATCHPB.fields_by_name['read_pairs'].message_type = _KEYVALUEPAIRPB
_KEYVALUEWRITEBATCHPB.fields_by_name['row_mark_type'].enum_type = yb_dot_common_dot_common__pb2._ROWMARKTYPE
_KEYVALUEWRITEBATCHPB.fields_by_name['apply_external_transactions'].message_type = _APPLYEXTERNALTRANSACTIONPB
_CONSENSUSFRONTIERPB.fields_by_name['op_id'].message_type = yb_dot_util_dot_opid__pb2._OPIDPB
DESCRIPTOR.message_types_by_name['KeyValuePairPB'] = _KEYVALUEPAIRPB
DESCRIPTOR.message_types_by_name['ApplyExternalTransactionPB'] = _APPLYEXTERNALTRANSACTIONPB
DESCRIPTOR.message_types_by_name['KeyValueWriteBatchPB'] = _KEYVALUEWRITEBATCHPB
DESCRIPTOR.message_types_by_name['ConsensusFrontierPB'] = _CONSENSUSFRONTIERPB
DESCRIPTOR.message_types_by_name['ApplyTransactionStatePB'] = _APPLYTRANSACTIONSTATEPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

KeyValuePairPB = _reflection.GeneratedProtocolMessageType('KeyValuePairPB', (_message.Message,), {
  'DESCRIPTOR' : _KEYVALUEPAIRPB,
  '__module__' : 'yb.docdb.docdb_pb2'
  # @@protoc_insertion_point(class_scope:yb.docdb.KeyValuePairPB)
  })
_sym_db.RegisterMessage(KeyValuePairPB)

ApplyExternalTransactionPB = _reflection.GeneratedProtocolMessageType('ApplyExternalTransactionPB', (_message.Message,), {
  'DESCRIPTOR' : _APPLYEXTERNALTRANSACTIONPB,
  '__module__' : 'yb.docdb.docdb_pb2'
  # @@protoc_insertion_point(class_scope:yb.docdb.ApplyExternalTransactionPB)
  })
_sym_db.RegisterMessage(ApplyExternalTransactionPB)

KeyValueWriteBatchPB = _reflection.GeneratedProtocolMessageType('KeyValueWriteBatchPB', (_message.Message,), {
  'DESCRIPTOR' : _KEYVALUEWRITEBATCHPB,
  '__module__' : 'yb.docdb.docdb_pb2'
  # @@protoc_insertion_point(class_scope:yb.docdb.KeyValueWriteBatchPB)
  })
_sym_db.RegisterMessage(KeyValueWriteBatchPB)

ConsensusFrontierPB = _reflection.GeneratedProtocolMessageType('ConsensusFrontierPB', (_message.Message,), {
  'DESCRIPTOR' : _CONSENSUSFRONTIERPB,
  '__module__' : 'yb.docdb.docdb_pb2'
  # @@protoc_insertion_point(class_scope:yb.docdb.ConsensusFrontierPB)
  })
_sym_db.RegisterMessage(ConsensusFrontierPB)

ApplyTransactionStatePB = _reflection.GeneratedProtocolMessageType('ApplyTransactionStatePB', (_message.Message,), {
  'DESCRIPTOR' : _APPLYTRANSACTIONSTATEPB,
  '__module__' : 'yb.docdb.docdb_pb2'
  # @@protoc_insertion_point(class_scope:yb.docdb.ApplyTransactionStatePB)
  })
_sym_db.RegisterMessage(ApplyTransactionStatePB)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
