// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package oapi

// AddContactGroupToPackageResponse defines model for AddContactGroupToPackageResponse.
type AddContactGroupToPackageResponse struct {
	ContactGroupId         *string   `json:"contactGroupId,omitempty"`
	ContactGroupName       *string   `json:"contactGroupName,omitempty"`
	ContactGroupUserEmails *[]string `json:"contactGroupUserEmails,omitempty"`
	Response               *string   `json:"response,omitempty"`
}

// AddContactGroupUserRequest defines model for AddContactGroupUserRequest.
type AddContactGroupUserRequest struct {
	UserEmail *string `json:"userEmail,omitempty"`
}

// AddContactGroupUserResponse defines model for AddContactGroupUserResponse.
type AddContactGroupUserResponse struct {
	Response  *string `json:"response,omitempty"`
	UserEmail *string `json:"userEmail,omitempty"`
	UserId    *string `json:"userId,omitempty"`
}

// AddDropzoneRecipientsResponse defines model for AddDropzoneRecipientsResponse.
type AddDropzoneRecipientsResponse struct {
	Message *struct {
		FailEmails    *[]string `json:"failEmails,omitempty"`
		Success       *string   `json:"success,omitempty"`
		SuccessEmails *[]string `json:"successEmails,omitempty"`
		WarnEmails    *[]string `json:"warnEmails,omitempty"`
	} `json:"message,omitempty"`
	Response *string `json:"response,omitempty"`
}

// AddKeyCodeToPackageResponse defines model for AddKeyCodeToPackageResponse.
type AddKeyCodeToPackageResponse struct {
	Message  *string `json:"message,omitempty"`
	Response *string `json:"response,omitempty"`
}

// AddPublicKeyRequest defines model for AddPublicKeyRequest.
type AddPublicKeyRequest struct {
	Description *string `json:"description,omitempty"`
	PublicKey   *string `json:"publicKey,omitempty"`
}

// AddPublicKeyResponse defines model for AddPublicKeyResponse.
type AddPublicKeyResponse struct {
	DateStr     *string `json:"dateStr,omitempty"`
	Description *string `json:"description,omitempty"`
	Id          *string `json:"id,omitempty"`
	Response    *string `json:"response,omitempty"`
}

// AddRecipientRequest defines model for AddRecipientRequest.
type AddRecipientRequest struct {
	Email string `json:"email"`
}

// AddRecipientResp defines model for AddRecipientResp.
type AddRecipientResp struct {
	ApprovalRequired   *bool   `json:"approvalRequired,omitempty"`
	CheckForPublicKeys *bool   `json:"checkForPublicKeys,omitempty"`
	Email              *string `json:"email,omitempty"`
	FullName           *string `json:"fullName,omitempty"`
	IsPackageOwner     *bool   `json:"isPackageOwner,omitempty"`
	Phonenumbers       *[]struct {
		CountryCode         *int  `json:"countryCode,omitempty"`
		Phonenumber         *int  `json:"phonenumber,omitempty"`
		WasUsedMostRecently *bool `json:"wasUsedMostRecently,omitempty"`
	} `json:"phonenumbers,omitempty"`
	RecipientId *string `json:"recipientId,omitempty"`
	Response    *string `json:"response,omitempty"`
	RoleName    *string `json:"roleName,omitempty"`
	SmsAuth     *bool   `json:"smsAuth,omitempty"`
}

// AddRecipientsRequest defines model for AddRecipientsRequest.
type AddRecipientsRequest struct {
	Emails *[]string `json:"emails,omitempty"`
}

// AddRecipientsToPackageResponse defines model for AddRecipientsToPackageResponse.
type AddRecipientsToPackageResponse struct {
	ApprovalRequired *bool                                      `json:"approvalRequired,omitempty"`
	Recipients       *[]GetPackageInformationResponseRecipients `json:"recipients,omitempty"`
	Response         *string                                    `json:"response,omitempty"`
}

// CopyFileRequest defines model for CopyFileRequest.
type CopyFileRequest struct {
	FileKey           *string `json:"fileKey,omitempty"`
	TargetDirectoryId *string `json:"targetDirectoryId,omitempty"`
	TargetPackageId   *string `json:"targetPackageId,omitempty"`
	UploadType        *string `json:"uploadType,omitempty"`
}

// CreateContactGroupRequest defines model for CreateContactGroupRequest.
type CreateContactGroupRequest struct {
	GroupName         *string `json:"groupName,omitempty"`
	IsEnterpriseGroup *bool   `json:"isEnterpriseGroup,omitempty"`
}

// CreateContactGroupResponse defines model for CreateContactGroupResponse.
type CreateContactGroupResponse struct {
	ContactGroupId         *string   `json:"contactGroupId,omitempty"`
	ContactGroupName       *string   `json:"contactGroupName,omitempty"`
	ContactGroupUserEmails *[]string `json:"contactGroupUserEmails,omitempty"`
	Response               *string   `json:"response,omitempty"`
}

// CreateDirectoryResponse defines model for CreateDirectoryResponse.
type CreateDirectoryResponse struct {
	Created     *string `json:"created,omitempty"`
	CreatedStr  *string `json:"createdStr,omitempty"`
	DirectoryId *string `json:"directoryId,omitempty"`
	Message     *string `json:"message,omitempty"`
	Name        *string `json:"name,omitempty"`
	Response    *string `json:"response,omitempty"`
}

// CreateFileRequest defines model for CreateFileRequest.
type CreateFileRequest struct {
	Filename *string  `json:"filename,omitempty"`
	Filesize *float32 `json:"filesize,omitempty"`
	Parts    *int     `json:"parts,omitempty"`
}

// CreateFileResp defines model for CreateFileResp.
type CreateFileResp struct {
	Message  *string `json:"message,omitempty"`
	Response *string `json:"response,omitempty"`
}

// CreatePackageRequest defines model for CreatePackageRequest.
type CreatePackageRequest struct {
	// Optional parameter that should only be set to true if creating a Workspace package
	Vdr *bool `json:"vdr,omitempty"`
}

// CreatePackageResp defines model for CreatePackageResp.
type CreatePackageResp struct {
	PackageCode  *string `json:"packageCode,omitempty"`
	PackageId    *string `json:"packageId,omitempty"`
	Response     *string `json:"response,omitempty"`
	ServerSecret *string `json:"serverSecret,omitempty"`
}

// CreateWorkspaceSubdirectoryRequest defines model for CreateWorkspaceSubdirectoryRequest.
type CreateWorkspaceSubdirectoryRequest struct {
	DirectoryName *string `json:"directoryName,omitempty"`
}

// DeleteContactGroupResponse defines model for DeleteContactGroupResponse.
type DeleteContactGroupResponse struct {
	Message  *string `json:"message,omitempty"`
	Response *string `json:"response,omitempty"`
}

// DeleteDropzoneRecipientResponse defines model for DeleteDropzoneRecipientResponse.
type DeleteDropzoneRecipientResponse struct {
	Message  *string `json:"message,omitempty"`
	Response *string `json:"response,omitempty"`
}

// DeleteFileResponse defines model for DeleteFileResponse.
type DeleteFileResponse struct {
	Message  *string `json:"message,omitempty"`
	Response *string `json:"response,omitempty"`
}

// DownloadUrlsResponse defines model for DownloadUrlsResponse.
type DownloadUrlsResponse struct {
	Part *int    `json:"part,omitempty"`
	Url  *string `json:"url,omitempty"`
}

// FinalizePackageRequest defines model for FinalizePackageRequest.
type FinalizePackageRequest struct {
	Checksum string `json:"checksum"`

	// Optional unless password is set
	Password *string `json:"password,omitempty"`

	// Optional, default is false, set to true if package has no recipients
	UndisclosedRecipients *bool `json:"undisclosedRecipients,omitempty"`
}

// FinalizePackageResp defines model for FinalizePackageResp.
type FinalizePackageResp struct {
	Approvers  *[]string `json:"approvers,omitempty"`
	Message    *string   `json:"message,omitempty"`
	NeedsLink  *bool     `json:"needsLink,omitempty"`
	Recipients *[]string `json:"recipients,omitempty"`
	Response   *string   `json:"response,omitempty"`
}

// GetActivityLogResponse defines model for GetActivityLogResponse.
type GetActivityLogResponse struct {
	ActivityLogEntries *[]struct {
		Action            *string `json:"action,omitempty"`
		ActionDescription *string `json:"actionDescription,omitempty"`
		ActivityLogId     *string `json:"activityLogId,omitempty"`
		IpAddress         *string `json:"ipAddress,omitempty"`
		PackageId         *string `json:"packageId,omitempty"`
		TargetId          *string `json:"targetId,omitempty"`
		Timestamp         *string `json:"timestamp,omitempty"`
		TimestampStr      *string `json:"timestampStr,omitempty"`
		User              *struct {
			UserEmail *string `json:"userEmail,omitempty"`
			UserId    *string `json:"userId,omitempty"`
		} `json:"user,omitempty"`
	} `json:"activityLogEntries,omitempty"`
	Response *string `json:"response,omitempty"`
}

// GetArchivedPackagesResponse defines model for GetArchivedPackagesResponse.
type GetArchivedPackagesResponse struct {
	Packages *[]struct {
		ContactGroups           *[]string `json:"contactGroups,omitempty"`
		Filenames               *[]string `json:"filenames,omitempty"`
		PackageBrowser          *string   `json:"packageBrowser,omitempty"`
		PackageCode             *string   `json:"packageCode,omitempty"`
		PackageContainsMessage  *bool     `json:"packageContainsMessage,omitempty"`
		PackageId               *string   `json:"packageId,omitempty"`
		PackageLife             *int      `json:"packageLife,omitempty"`
		PackageOS               *string   `json:"packageOS,omitempty"`
		PackageOriginatorUserId *string   `json:"packageOriginatorUserId,omitempty"`
		PackageParentId         *string   `json:"packageParentId,omitempty"`

		// This provides the numeric representation of package state. What follows is a mapping of packageState and the corresponding packageStateStr value: 1 Expired - Not Picked Up | 2 Expired - Pickup | 3 Active - Pickup Complete | 4 Active - Waiting for Pickup | 5 Active - Pickup In Progress |  6 Complete Expired - Pickup In Progress | 0 - In Progess | -1 Deleted - Pickup Complete | -2 TEMP | -3 Deleted - Not Picked Up | -4 Deleted - Pickup In Progress
		PackageState *int `json:"packageState,omitempty"`

		// color in hex code
		PackageStateColor *string `json:"packageStateColor",omitempty"`

		// String representation of the packageState property. What follows is a listing of possible packageStateStr values: Expired - Not Picked Up | Expired - Pickup | Active - Pickup Complete | Active - Waiting for Pickup | Active - Pickup In Progress | Complete Expired - Pickup In Progress | In Progess | Deleted - Pickup Complete | TEMP | Deleted - Not Picked Up | Deleted - Pickup In Progress
		PackageStateStr *string `json:"packageStateStr,omitempty"`

		// Package Creation TimeStamp
		PackageUpdateTimestamp *string `json:"packageUpdateTimestamp,omitempty"`

		// Package Creation TimeStamp
		PackageUpdateTimestampStr *string   `json:"packageUpdateTimestampStr",omitempty"`
		PackageUserName           *string   `json:"packageUserName,omitempty"`
		RecipientCount            *int      `json:"recipientCount,omitempty"`
		Recipients                *[]string `json:"recipients,omitempty"`
		TimeZone                  *string   `json:"timeZone,omitempty"`
	} `json:"packages,omitempty"`
}

// GetDirectoryResponse defines model for GetDirectoryResponse.
type GetDirectoryResponse struct {
	DirectoryId    *string                   `json:"directoryId,omitempty"`
	DirectoryName  *string                   `json:"directoryName,omitempty"`
	Files          *[]map[string]interface{} `json:"files,omitempty"`
	Response       *string                   `json:"response,omitempty"`
	SubDirectories *[]map[string]interface{} `json:"subDirectories,omitempty"`
}

// GetDownloadUrlsRequest defines model for GetDownloadUrlsRequest.
type GetDownloadUrlsRequest struct {
	// HmacSHA256(keycode,packageCode)
	Checksum *string `json:"checksum,omitempty"`

	// The file part number you would like as the ending point for this group of URLs. No more than 25 file parts are returned at once.
	EndSegment *int `json:"endSegment,omitempty"`

	// The file part number you would like as the starting point for this group of URLs. No more than 25 file parts are returned at once.
	StartSegment *int `json:"startSegment,omitempty"`
}

// GetDownloadUrlsResponse defines model for GetDownloadUrlsResponse.
type GetDownloadUrlsResponse struct {
	DownloadUrls *[]DownloadUrlsResponse `json:"downloadUrls,omitempty"`
	Response     *string                 `json:"response,omitempty"`
}

// GetDropzoneRecipientsResponse defines model for GetDropzoneRecipientsResponse.
type GetDropzoneRecipientsResponse struct {
	RecipientEmailAddresses *[]string `json:"recipientEmailAddresses,omitempty"`
	Response                *string   `json:"response,omitempty"`
}

// GetEnterpriseContactGroupsResponse defines model for GetEnterpriseContactGroupsResponse.
type GetEnterpriseContactGroupsResponse struct {
	ContactGroups *[]struct {
		ContactGroupId                  *string `json:"contactGroupId,omitempty"`
		ContactGroupIsOrganizationGroup *bool   `json:"contactGroupIsOrganizationGroup,omitempty"`
		ContactGroupName                *string `json:"contactGroupName,omitempty"`
		Users                           *[]struct {
			UserEmail *string `json:"userEmail,omitempty"`
			UserId    *string `json:"userId,omitempty"`
		} `json:"users,omitempty"`
	} `json:"contactGroups,omitempty"`
	Response *string `json:"response,omitempty"`
}

// GetEnterpriseInfoResponse defines model for GetEnterpriseInfoResponse.
type GetEnterpriseInfoResponse struct {
	AllowUndisclosedRecipients *bool   `json:"allowUndisclosedRecipients,omitempty"`
	Host                       *string `json:"host,omitempty"`
	LinkColor                  *string `json:"linkColor,omitempty"`
	MessageEncryption          *bool   `json:"messageEncryption,omitempty"`
	OutlookBeta                *bool   `json:"outlookBeta,omitempty"`
	Response                   *string `json:"response,omitempty"`
	SystemName                 *string `json:"systemName,omitempty"`
}

// GetFileResponse defines model for GetFileResponse.
type GetFileResponse struct {
	File *struct {
		File *struct {
			CreatedByEmail *string `json:"createdByEmail,omitempty"`
			FileId         *string `json:"fileId,omitempty"`
			FileName       *string `json:"fileName,omitempty"`
			FileParts      *int    `json:"fileParts,omitempty"`
			FileSize       *string `json:"fileSize,omitempty"`
			OldVersions    *[]struct {
				CreatedByEmail *string `json:"createdByEmail,omitempty"`
				FileId         *string `json:"fileId,omitempty"`
				FileName       *string `json:"fileName,omitempty"`
				FileParts      *int    `json:"fileParts,omitempty"`
				FileSize       *string `json:"fileSize,omitempty"`
				Uploaded       *string `json:"uploaded,omitempty"`
				UploadedStr    *string `json:"uploadedStr,omitempty"`
			} `json:"oldVersions,omitempty"`
			Uploaded    *string `json:"uploaded,omitempty"`
			UploadedStr *string `json:"uploadedStr,omitempty"`
		} `json:"file,omitempty"`
	} `json:"file,omitempty"`
	Response *string `json:"response,omitempty"`
}

// GetIdentityCookieResponse defines model for GetIdentityCookieResponse.
type GetIdentityCookieResponse struct {
	Domain   *string `json:"domain,omitempty"`
	Name     *string `json:"name,omitempty"`
	Response *string `json:"response,omitempty"`
	Value    *string `json:"value,omitempty"`
}

// GetOrganizationPackagesRequest defines model for GetOrganizationPackagesRequest.
type GetOrganizationPackagesRequest struct {
	Filename *string `json:"filename,omitempty"`

	// 01/01/2019
	FromDate *string `json:"fromDate,omitempty"`

	// test@sendsafely.com
	Recipient *string `json:"recipient,omitempty"`

	// test@sendsafely.com
	Sender *string `json:"sender,omitempty"`

	// all | picked-up | incomplete | archived | active | expired
	Status *string `json:"status,omitempty"`

	// 01/01/2019
	ToDate *string `json:"toDate,omitempty"`
}

// GetOrganizationPackagesResp defines model for GetOrganizationPackagesResp.
type GetOrganizationPackagesResp struct {
	Packages *[]GetPackageInformationResp `json:"packages,omitempty"`
}

// GetPackageInformationResp defines model for GetPackageInformationResp.
type GetPackageInformationResp struct {
	ApproverList     *[]GetPackageInformationResponseApproverList  `json:"approverList,omitempty"`
	ContactGroups    *[]GetPackageInformationResponseContactGroups `json:"contactGroups,omitempty"`
	Directories      *[]GetPackageInformationResponseContactGroups `json:"directories,omitempty"`
	Files            *[]GetPackageInformationResponseContactGroups `json:"files,omitempty"`
	IsArchived       *bool                                         `json:"isArchived,omitempty"`
	IsVDR            *bool                                         `json:"isVDR,omitempty"`
	Life             *int                                          `json:"life,omitempty"`
	NeedsApproval    *bool                                         `json:"needsApproval,omitempty"`
	PackageCode      *string                                       `json:"packageCode,omitempty"`
	PackageId        *string                                       `json:"packageId,omitempty"`
	PackageSender    *string                                       `json:"packageSender,omitempty"`
	PackageTimestamp *string                                       `json:"packageTimestamp,omitempty"`
	PasswordRequired *bool                                         `json:"passwordRequired,omitempty"`
	Recipients       *[]GetPackageInformationResponseRecipients    `json:"recipients,omitempty"`
	Response         *string                                       `json:"response,omitempty"`
	RootDirectoryId  *string                                       `json:"rootDirectoryId,omitempty"`
	ServerSecret     *string                                       `json:"serverSecret,omitempty"`
	State            *string                                       `json:"state,omitempty"`
}

// GetPackageInformationResponseApproverList defines model for GetPackageInformationResponse_approverList.
type GetPackageInformationResponseApproverList = map[string]interface{}

// GetPackageInformationResponseConfirmations defines model for GetPackageInformationResponse_confirmations.
type GetPackageInformationResponseConfirmations struct {
	IpAddress    *string `json:"ipAddress,omitempty"`
	IsMessage    *bool   `json:"isMessage,omitempty"`
	TimeStampStr *string `json:"timeStampStr,omitempty"`
	Timestamp    *string `json:"timestamp,omitempty"`
}

// GetPackageInformationResponseContactGroups defines model for GetPackageInformationResponse_contactGroups.
type GetPackageInformationResponseContactGroups struct {
	Id *string `json:"id,omitempty"`
}

// GetPackageInformationResponseRecipients defines model for GetPackageInformationResponse_recipients.
type GetPackageInformationResponseRecipients struct {
	CheckForPublicKeys *bool                                         `json:"checkForPublicKeys,omitempty"`
	Confirmations      *[]GetPackageInformationResponseConfirmations `json:"confirmations,omitempty"`
	Email              *string                                       `json:"email,omitempty"`
	FullName           *string                                       `json:"fullName,omitempty"`
	IsPackageOwner     *bool                                         `json:"isPackageOwner,omitempty"`
	NeedsApproval      *bool                                         `json:"needsApproval,omitempty"`
	RecipientCode      *string                                       `json:"recipientCode,omitempty"`
	RecipientId        *string                                       `json:"recipientId,omitempty"`
	RoleName           *string                                       `json:"roleName,omitempty"`
}

// GetPackageMessageResponse defines model for GetPackageMessageResponse.
type GetPackageMessageResponse struct {
	Message  *string `json:"message,omitempty"`
	Response *string `json:"response,omitempty"`
}

// GetPublicKeyResponse defines model for GetPublicKeyResponse.
type GetPublicKeyResponse struct {
	Id        *string `json:"id,omitempty"`
	PublicKey *string `json:"publicKey,omitempty"`
	Response  *string `json:"response,omitempty"`
}

// GetPublicKeysResponse defines model for GetPublicKeysResponse.
type GetPublicKeysResponse struct {
	PublicKeys *[]struct {
		Id  *string `json:"id,omitempty"`
		Key *string `json:"key,omitempty"`
	} `json:"publicKeys,omitempty"`
	Response *string `json:"response,omitempty"`
}

// GetReceivedPackagesResponse defines model for GetReceivedPackagesResponse.
type GetReceivedPackagesResponse struct {
	Packages *[]struct {
		Filenames               *[]string `json:"filenames,omitempty"`
		PackageBrowser          *string   `json:"packageBrowser,omitempty"`
		PackageCode             *string   `json:"packageCode,omitempty"`
		PackageContainsMessage  *bool     `json:"packageContainsMessage,omitempty"`
		PackageId               *string   `json:"packageId,omitempty"`
		PackageOS               *string   `json:"packageOS,omitempty"`
		PackageOriginatorUserId *string   `json:"packageOriginatorUserId,omitempty"`
		PackageParentId         *string   `json:"packageParentId,omitempty"`

		// This provides the numeric representation of package state. What follows is a mapping of packageState and the corresponding packageStateStr value: 1 Expired - Not Picked Up | 2 Expired - Pickup | 3 Active - Pickup Complete | 4 Active - Waiting for Pickup | 5 Active - Pickup In Progress |  6 Complete Expired - Pickup In Progress | 0 - In Progess | -1 Deleted - Pickup Complete | -2 TEMP | -3 Deleted - Not Picked Up | -4 Deleted - Pickup In Progress
		PackageState *int `json:"packageState,omitempty"`

		// color in hex code
		PackageStateColor *string `json:"packageStateColor",omitempty"`

		// String representation of the packageState property. What follows is a listing of possible packageStateStr values: Expired - Not Picked Up | Expired - Pickup | Active - Pickup Complete | Active - Waiting for Pickup | Active - Pickup In Progress | Complete Expired - Pickup In Progress | In Progess | Deleted - Pickup Complete | TEMP | Deleted - Not Picked Up | Deleted - Pickup In Progress
		PackageStateStr *string `json:"packageStateStr,omitempty"`

		// Package Creation TimeStamp
		PackageUpdateTimestamp *string `json:"packageUpdateTimestamp,omitempty"`

		// Package Creation TimeStamp
		PackageUpdateTimestampStr *string `json:"packageUpdateTimestampStr",omitempty"`
		PackageUserName           *string `json:"packageUserName,omitempty"`
		TimeZone                  *string `json:"timeZone,omitempty"`
	} `json:"packages,omitempty"`
}

// GetRecipientHistoryResponse defines model for GetRecipientHistoryResponse.
type GetRecipientHistoryResponse struct {
	Message  *string                            `json:"message,omitempty"`
	Packages *[]RecipientHistoryPackageResponse `json:"packages,omitempty"`
	Response *string                            `json:"response,omitempty"`
}

// GetSentPackagesResponse defines model for GetSentPackagesResponse.
type GetSentPackagesResponse struct {
	Packages *[]struct {
		ContactGroups          *[]string `json:"contactGroups,omitempty"`
		Filenames              *[]string `json:"filenames,omitempty"`
		PackageBrowser         *string   `json:"packageBrowser,omitempty"`
		PackageCode            *string   `json:"packageCode,omitempty"`
		PackageContainsMessage *bool     `json:"packageContainsMessage,omitempty"`
		PackageId              *string   `json:"packageId,omitempty"`
		PackageLife            *int      `json:"packageLife,omitempty"`
		PackageOS              *string   `json:"packageOS,omitempty"`
		PackageParentId        *string   `json:"packageParentId,omitempty"`

		// This provides the numeric representation of package state. What follows is a mapping of packageState and the corresponding packageStateStr value: 1 Expired - Not Picked Up | 2 Expired - Pickup | 3 Active - Pickup Complete | 4 Active - Waiting for Pickup | 5 Active - Pickup In Progress |  6 Complete Expired - Pickup In Progress | 0 - In Progess | -1 Deleted - Pickup Complete | -2 TEMP | -3 Deleted - Not Picked Up | -4 Deleted - Pickup In Progress
		PackageState *int `json:"packageState,omitempty"`

		// color in hex code
		PackageStateColor *string `json:"packageStateColor",omitempty"`

		// String representation of the packageState property. What follows is a listing of possible packageStateStr values: Expired - Not Picked Up | Expired - Pickup | Active - Pickup Complete | Active - Waiting for Pickup | Active - Pickup In Progress | Complete Expired - Pickup In Progress | In Progess | Deleted - Pickup Complete | TEMP | Deleted - Not Picked Up | Deleted - Pickup In Progress
		PackageStateStr *string `json:"packageStateStr,omitempty"`

		// Package Creation TimeStamp
		PackageUpdateTimestamp *string `json:"packageUpdateTimestamp,omitempty"`

		// Package Creation TimeStamp
		PackageUpdateTimestampStr *string   `json:"packageUpdateTimestampStr",omitempty"`
		PackageUserId             *string   `json:"packageUserId,omitempty"`
		PackageUserName           *string   `json:"packageUserName,omitempty"`
		RecipientCount            *int      `json:"recipientCount,omitempty"`
		Recipients                *[]string `json:"recipients,omitempty"`
	} `json:"packages,omitempty"`
}

// GetUploadUrlsRequest defines model for GetUploadUrlsRequest.
type GetUploadUrlsRequest struct {
	// The file part number you would like as the starting point for this group of URLs. No more than 25 file parts are returned at once.
	Part int `json:"part"`
}

// GetUploadUrlsResp defines model for GetUploadUrlsResp.
type GetUploadUrlsResp struct {
	UploadUrls *[]GetUploadUrlsResponseUploadUrls `json:"uploadUrls,omitempty"`
}

// GetUploadUrlsResponseUploadUrls defines model for GetUploadUrlsResponse_uploadUrls.
type GetUploadUrlsResponseUploadUrls struct {
	Part *int    `json:"part,omitempty"`
	Url  *string `json:"url,omitempty"`
}

// GetUserContactGroupsResponse defines model for GetUserContactGroupsResponse.
type GetUserContactGroupsResponse struct {
	ContactGroups *[]struct {
		ContactGroupId                  *string `json:"contactGroupId,omitempty"`
		ContactGroupIsOrganizationGroup *bool   `json:"contactGroupIsOrganizationGroup,omitempty"`
		ContactGroupName                *string `json:"contactGroupName,omitempty"`
		Users                           *[]struct {
			UserEmail *string `json:"userEmail,omitempty"`
			UserId    *string `json:"userId,omitempty"`
		} `json:"users,omitempty"`
	} `json:"contactGroups,omitempty"`
	Response *string `json:"response,omitempty"`
}

// GetUserInformationResponse defines model for GetUserInformationResponse.
type GetUserInformationResponse struct {
	AdminUser   *bool   `json:"adminUser,omitempty"`
	BetaUser    *bool   `json:"betaUser,omitempty"`
	ClientKey   *string `json:"clientKey,omitempty"`
	Email       *string `json:"email,omitempty"`
	FirstName   *string `json:"firstName,omitempty"`
	Id          *string `json:"id,omitempty"`
	LastName    *string `json:"lastName,omitempty"`
	PackageLife *int    `json:"packageLife,omitempty"`
	PublicKey   *bool   `json:"publicKey,omitempty"`
	Response    *string `json:"response,omitempty"`
}

// GetWorkspacePackagesResponse defines model for GetWorkspacePackagesResponse.
type GetWorkspacePackagesResponse struct {
	Packages *[]struct {
		PackageCode            *string `json:"packageCode,omitempty"`
		PackageContainsMessage *bool   `json:"packageContainsMessage,omitempty"`
		PackageId              *string `json:"packageId,omitempty"`

		// workspace name
		PackageLabel *string `json:"packageLabel,omitempty"`
		PackageLife  *int    `json:"packageLife,omitempty"`

		// This provides the numeric representation of package state. What follows is a mapping of packageState and the corresponding packageStateStr value: 1 Expired - Not Picked Up | 2 Expired - Pickup | 3 Active - Pickup Complete | 4 Active - Waiting for Pickup | 5 Active - Pickup In Progress |  6 Complete Expired - Pickup In Progress | 0 - In Progess | -1 Deleted - Pickup Complete | -2 TEMP | -3 Deleted - Not Picked Up | -4 Deleted - Pickup In Progress
		PackageState *int `json:"packageState,omitempty"`

		// String representation of the packageState property. What follows is a listing of possible packageStateStr values: Expired - Not Picked Up | Expired - Pickup | Active - Pickup Complete | Active - Waiting for Pickup | Active - Pickup In Progress | Complete Expired - Pickup In Progress | In Progess | Deleted - Pickup Complete | TEMP | Deleted - Not Picked Up | Deleted - Pickup In Progress
		PackageStateStr *string `json:"packageStateStr,omitempty"`

		// Last Modified TimeStamp
		PackageUpdateTimestamp *string `json:"packageUpdateTimestamp,omitempty"`

		// Last modified TimeStamp
		PackageUpdateTimestampStr *string `json:"packageUpdateTimestampStr,omitempty"`
		PackageUserId             *string `json:"packageUserId,omitempty"`
		PackageUserName           *string `json:"packageUserName,omitempty"`
	} `json:"packages,omitempty"`
}

// MoveWorkspaceFileResponse defines model for MoveWorkspaceFileResponse.
type MoveWorkspaceFileResponse struct {
	DirectoryId *string `json:"directoryId,omitempty"`
	Response    *string `json:"response,omitempty"`
}

// RecipientHistoryPackageResponse defines model for RecipientHistoryPackageResponse.
type RecipientHistoryPackageResponse struct {
	Filenames              *[]string                          `json:"filenames,omitempty"`
	PackageBrowser         *string                            `json:"packageBrowser,omitempty"`
	PackageContainsMessage *bool                              `json:"packageContainsMessage,omitempty"`
	PackageId              *string                            `json:"packageId,omitempty"`
	PackageLife            *int                               `json:"packageLife,omitempty"`
	PackageOS              *string                            `json:"packageOS,omitempty"`
	PackageState           *int                               `json:"packageState,omitempty"`
	PackageUserId          *string                            `json:"packageUserId,omitempty"`
	PackageUserName        *string                            `json:"packageUserName,omitempty"`
	Recipient              *RecipientHistoryRecipientResponse `json:"recipient,omitempty"`
}

// RecipientHistoryRecipientResponse defines model for RecipientHistoryRecipientResponse.
type RecipientHistoryRecipientResponse struct {
	CheckForPublicKeys *bool                                         `json:"checkForPublicKeys,omitempty"`
	Confirmations      *[]GetPackageInformationResponseConfirmations `json:"confirmations,omitempty"`
	Email              *string                                       `json:"email,omitempty"`
	IsPackageOwner     *bool                                         `json:"isPackageOwner,omitempty"`
	NeedsApproval      *bool                                         `json:"needsApproval,omitempty"`
	RecipientId        *string                                       `json:"recipientId,omitempty"`
}

// RenameWorkspaceDirectoryRequest defines model for RenameWorkspaceDirectoryRequest.
type RenameWorkspaceDirectoryRequest struct {
	// Workspace directory name
	DirectoryName *string `json:"directoryName,omitempty"`
}

// SuccessResponse defines model for SuccessResponse.
type SuccessResponse struct {
	Response *string `json:"response,omitempty"`
}

// SyncKeycodesResponse defines model for SyncKeycodesResponse.
type SyncKeycodesResponse struct {
	Keycodes   *[]string `json:"keycodes,omitempty"`
	PublicKeys *[]struct {
		Id  *string `json:"id,omitempty"`
		Key *string `json:"key,omitempty"`
	} `json:"publicKeys,omitempty"`
	Response *string `json:"response,omitempty"`
}

// UpdateDropzoneConfigResponse defines model for UpdateDropzoneConfigResponse.
type UpdateDropzoneConfigResponse struct {
	DropzoneEnableSecureMessage   *bool     `json:"dropzoneEnableSecureMessage,omitempty"`
	DropzoneExternalPostUrl       *string   `json:"dropzoneExternalPostUrl,omitempty"`
	DropzoneLife                  *int      `json:"dropzoneLife,omitempty"`
	DropzoneNotificationType      *int      `json:"dropzoneNotificationType,omitempty"`
	DropzoneRecipients            *[]string `json:"dropzoneRecipients,omitempty"`
	DropzoneRequireAuthentication *bool     `json:"dropzoneRequireAuthentication,omitempty"`
	DropzoneTextLabel             *string   `json:"dropzoneTextLabel,omitempty"`
	DropzoneUrl                   *string   `json:"dropzoneUrl,omitempty"`
	IsDropzoneEnabled             *bool     `json:"isDropzoneEnabled,omitempty"`
	Message                       *string   `json:"message,omitempty"`
	PublicKey                     *string   `json:"publicKey,omitempty"`
	PublicSecret                  *string   `json:"publicSecret,omitempty"`
	Response                      *string   `json:"response,omitempty"`
}

// UpdateDropzoneRequest defines model for UpdateDropzoneRequest.
type UpdateDropzoneRequest struct {
	// true to enable secure message
	DropzoneEnableMessage *bool `json:"dropzoneEnableMessage,omitempty"`

	// 0 for Do not notify recipients, 1 for notify via email with trusted browser, 2 for notify via email with untrusted browser
	DropzoneNotificationType *int `json:"dropzoneNotificationType,omitempty"`

	// https://test.com
	DropzonePostUrl *string `json:"dropzonePostUrl,omitempty"`

	// true to request users to verify email address
	DropzoneRequireAuthentication *bool `json:"dropzoneRequireAuthentication,omitempty"`

	// true to restrict download and allow preview of pdf and images only
	DropzoneRestrictDownload *bool   `json:"dropzoneRestrictDownload,omitempty"`
	DropzoneTextLabel        *string `json:"dropzoneTextLabel,omitempty"`
}

// UpdatePackageInformationRequest defines model for UpdatePackageInformationRequest.
type UpdatePackageInformationRequest struct {
	// HmacSHA256(keycode,packageCode) - Can only be set on a Workspace and by users with the Owner or Manager role.
	Checksum *string `json:"checksum,omitempty"`

	// Only applicable to workspaces
	Label *string `json:"label,omitempty"`

	// Only applicable to non-workspace packages
	Life *int `json:"life,omitempty"`
}

// UpdateRecipientRequest defines model for UpdateRecipientRequest.
type UpdateRecipientRequest struct {
	// US
	Countrycode *string `json:"countrycode,omitempty"`

	// (123) 456-7890
	PhoneNumber *string `json:"phoneNumber,omitempty"`

	// VIEWER | CONTRIBUTOR | MANAGER | OWNER
	Role *string `json:"role,omitempty"`
}

// UploadCompletedRequest defines model for UploadCompletedRequest.
type UploadCompletedRequest struct {
	Complete bool `json:"complete"`
}

// UploadCompletedResponse defines model for UploadCompletedResponse.
type UploadCompletedResponse struct {
	Message  *string `json:"message,omitempty"`
	Response *string `json:"response,omitempty"`
}

// UploadEncryptedMessageRequest defines model for UploadEncryptedMessageRequest.
type UploadEncryptedMessageRequest struct {
	Message string `json:"message"`
}

// UploadEncryptedMessageResp defines model for UploadEncryptedMessageResp.
type UploadEncryptedMessageResp struct {
	Message  *string `json:"message,omitempty"`
	Response *string `json:"response,omitempty"`
}

// VerifyCredentialsResponse defines model for VerifyCredentialsResponse.
type VerifyCredentialsResponse struct {
	Message          *string `json:"message,omitempty"`
	RequiresApprover *bool   `json:"requiresApprover,omitempty"`
	Response         *string `json:"response,omitempty"`
}

// PageParam defines model for pageParam.
type PageParam = int

// RowParam defines model for rowParam.
type RowParam = int

// SortFieldParam defines model for sortFieldParam.
type SortFieldParam = string

// SortOrderParam defines model for sortOrderParam.
type SortOrderParam = string

// WorkspaceSortFieldParam defines model for workspaceSortFieldParam.
type WorkspaceSortFieldParam = string

// GetConfigVerifyCredentialsParams defines parameters for GetConfigVerifyCredentials.
type GetConfigVerifyCredentialsParams struct {
	SsApiKey           string `json:"ss-api-key"`
	SsRequestSignature string `json:"ss-request-signature"`
	SsRequestTimestamp string `json:"ss-request-timestamp"`
	ContentType        string `json:"content-type"`
}

// GetEnterpriseParams defines parameters for GetEnterprise.
type GetEnterpriseParams struct {
	SsApiKey           string `json:"ss-api-key"`
	SsRequestSignature string `json:"ss-request-signature"`
	SsRequestTimestamp string `json:"ss-request-timestamp"`
	ContentType        string `json:"content-type"`
}

// GetEnterpriseGroupsParams defines parameters for GetEnterpriseGroups.
type GetEnterpriseGroupsParams struct {
	SsApiKey           string `json:"ss-api-key"`
	SsRequestSignature string `json:"ss-request-signature"`
	SsRequestTimestamp string `json:"ss-request-timestamp"`
	ContentType        string `json:"content-type"`
}

// GetGetIdentityCookieParams defines parameters for GetGetIdentityCookie.
type GetGetIdentityCookieParams struct {
	SsApiKey           string `json:"ss-api-key"`
	SsRequestSignature string `json:"ss-request-signature"`
	SsRequestTimestamp string `json:"ss-request-timestamp"`
	ContentType        string `json:"content-type"`
}

// PutGroupJSONBody defines parameters for PutGroup.
type PutGroupJSONBody = CreateContactGroupRequest

// PutGroupParams defines parameters for PutGroup.
type PutGroupParams struct {
	SsApiKey           string `json:"ss-api-key"`
	SsRequestSignature string `json:"ss-request-signature"`
	SsRequestTimestamp string `json:"ss-request-timestamp"`
}

// DeleteGroupGroupIdParams defines parameters for DeleteGroupGroupId.
type DeleteGroupGroupIdParams struct {
	SsApiKey           string `json:"ss-api-key"`
	SsRequestSignature string `json:"ss-request-signature"`
	SsRequestTimestamp string `json:"ss-request-timestamp"`
}

// PutGroupGroupIdUserJSONBody defines parameters for PutGroupGroupIdUser.
type PutGroupGroupIdUserJSONBody = AddContactGroupUserRequest

// PutGroupGroupIdUserParams defines parameters for PutGroupGroupIdUser.
type PutGroupGroupIdUserParams struct {
	SsApiKey           string `json:"ss-api-key"`
	SsRequestSignature string `json:"ss-request-signature"`
	SsRequestTimestamp string `json:"ss-request-timestamp"`
}

// DeleteGroupGroupIdUserIdParams defines parameters for DeleteGroupGroupIdUserId.
type DeleteGroupGroupIdUserIdParams struct {
	SsApiKey           string `json:"ss-api-key"`
	SsRequestSignature string `json:"ss-request-signature"`
	SsRequestTimestamp string `json:"ss-request-timestamp"`
}

// GetPackageParams defines parameters for GetPackage.
type GetPackageParams struct {
	// Starting row for data
	RowIndex *RowParam `form:"rowIndex,omitempty" json:"rowIndex,omitempty"`

	// Number of rows to return, maximum of 100
	PageSize *PageParam `form:"pageSize,omitempty" json:"pageSize,omitempty"`

	// SendSafely API Key (API_KEY)
	SsApiKey string `json:"ss-api-key"`

	// TIMESTAMP (ex: 2014-01-14T22:24:00+0000)
	SsRequestTimestamp string `json:"ss-request-timestamp"`

	// HmacSHA256(API_SECRET, API_KEY + URL_PATH + TIMESTAMP + REQUEST_BODY)
	SsRequestSignature string `json:"ss-request-signature"`
}

// CreatePackageJSONBody defines parameters for CreatePackage.
type CreatePackageJSONBody = CreatePackageRequest

// CreatePackageParams defines parameters for CreatePackage.
type CreatePackageParams struct {
	// SendSafely API Key (API_KEY)
	SsApiKey string `json:"ss-api-key"`

	// TIMESTAMP (ex: 2014-01-14T22:24:00+0000)
	SsRequestTimestamp string `json:"ss-request-timestamp"`

	// HmacSHA256(API_SECRET, API_KEY + URL_PATH + TIMESTAMP + REQUEST_BODY)
	SsRequestSignature string `json:"ss-request-signature"`
}

// GetPackageArchivedParams defines parameters for GetPackageArchived.
type GetPackageArchivedParams struct {
	// Starting row for data
	RowIndex *RowParam `form:"rowIndex,omitempty" json:"rowIndex,omitempty"`

	// Number of rows to return, maximum of 100
	PageSize           *PageParam `form:"pageSize,omitempty" json:"pageSize,omitempty"`
	SsApiKey           string     `json:"ss-api-key"`
	SsRequestSignature string     `json:"ss-request-signature"`
	SsRequestTimestamp string     `json:"ss-request-timestamp"`
}

// GetOrganizationPackagesJSONBody defines parameters for GetOrganizationPackages.
type GetOrganizationPackagesJSONBody = GetOrganizationPackagesRequest

// GetOrganizationPackagesParams defines parameters for GetOrganizationPackages.
type GetOrganizationPackagesParams struct {
	// Starting row for data
	RowIndex *RowParam `form:"rowIndex,omitempty" json:"rowIndex,omitempty"`

	// Number of rows to return, maximum of 100
	PageSize           *PageParam `form:"pageSize,omitempty" json:"pageSize,omitempty"`
	SsApiKey           string     `json:"ss-api-key"`
	SsRequestTimestamp string     `json:"ss-request-timestamp"`
	SsRequestSignature string     `json:"ss-request-signature"`
}

// GetPackageReceivedParams defines parameters for GetPackageReceived.
type GetPackageReceivedParams struct {
	// Starting row for data
	RowIndex *RowParam `form:"rowIndex,omitempty" json:"rowIndex,omitempty"`

	// Number of rows to return, maximum of 100
	PageSize           *PageParam `form:"pageSize,omitempty" json:"pageSize,omitempty"`
	SsApiKey           string     `json:"ss-api-key"`
	SsRequestSignature string     `json:"ss-request-signature"`
	SsRequestTimestamp string     `json:"ss-request-timestamp"`
}

// GetPackageWorkspacesParams defines parameters for GetPackageWorkspaces.
type GetPackageWorkspacesParams struct {
	// Starting row for data
	RowIndex *RowParam `form:"rowIndex,omitempty" json:"rowIndex,omitempty"`

	// Number of rows to return, maximum of 100
	PageSize *PageParam `form:"pageSize,omitempty" json:"pageSize,omitempty"`

	// Column field for sorting
	SortField *WorkspaceSortFieldParam `form:"sortField,omitempty" json:"sortField,omitempty"`

	// Sort ordering
	SortOrder *SortOrderParam `form:"sortOrder,omitempty" json:"sortOrder,omitempty"`

	// SendSafely API Key (API_KEY)
	SsApiKey string `json:"ss-api-key"`

	// TIMESTAMP (ex: 2014-01-14T22:24:00+0000)
	SsRequestTimestamp string `json:"ss-request-timestamp"`

	// HmacSHA256(API_SECRET, API_KEY + URL_PATH + TIMESTAMP + REQUEST_BODY)
	SsRequestSignature string `json:"ss-request-signature"`
}

// DeletePackagePackageIdParams defines parameters for DeletePackagePackageId.
type DeletePackagePackageIdParams struct {
	SsApiKey           string `json:"ss-api-key"`
	SsRequestSignature string `json:"ss-request-signature"`
	SsRequestTimestamp string `json:"ss-request-timestamp"`
}

// GetPackageInformationParams defines parameters for GetPackageInformation.
type GetPackageInformationParams struct {
	SsApiKey           string `json:"ss-api-key"`
	SsRequestTimestamp string `json:"ss-request-timestamp"`
	SsRequestSignature string `json:"ss-request-signature"`
}

// PostPackagePackageIdJSONBody defines parameters for PostPackagePackageId.
type PostPackagePackageIdJSONBody = UpdatePackageInformationRequest

// PostPackagePackageIdParams defines parameters for PostPackagePackageId.
type PostPackagePackageIdParams struct {
	SsApiKey           string `json:"ss-api-key"`
	SsRequestSignature string `json:"ss-request-signature"`
	SsRequestTimestamp string `json:"ss-request-timestamp"`
}

// PostPackagePackageIdActivityLogParams defines parameters for PostPackagePackageIdActivityLog.
type PostPackagePackageIdActivityLogParams struct {
	SsApiKey           string `json:"ss-api-key"`
	SsRequestSignature string `json:"ss-request-signature"`
	SsRequestTimestamp string `json:"ss-request-timestamp"`
}

// GetPackagePackageIdDirectoryDirectoryIdParams defines parameters for GetPackagePackageIdDirectoryDirectoryId.
type GetPackagePackageIdDirectoryDirectoryIdParams struct {
	// The index for paging subdirectories within the current directory
	DirectoryIndex *int `form:"directoryIndex,omitempty" json:"directoryIndex,omitempty"`

	// The index for paging files within the current directory
	FileIndex *int `form:"fileIndex,omitempty" json:"fileIndex,omitempty"`

	// Column field for sorting
	SortField *SortFieldParam `form:"sortField,omitempty" json:"sortField,omitempty"`

	// Sort ordering
	SortOrder          *SortOrderParam `form:"sortOrder,omitempty" json:"sortOrder,omitempty"`
	SsApiKey           string          `json:"ss-api-key"`
	SsRequestSignature string          `json:"ss-request-signature"`
	SsRequestTimestamp string          `json:"ss-request-timestamp"`
}

// PostPackagePackageIdDirectoryDirectoryIdJSONBody defines parameters for PostPackagePackageIdDirectoryDirectoryId.
type PostPackagePackageIdDirectoryDirectoryIdJSONBody = RenameWorkspaceDirectoryRequest

// PostPackagePackageIdDirectoryDirectoryIdParams defines parameters for PostPackagePackageIdDirectoryDirectoryId.
type PostPackagePackageIdDirectoryDirectoryIdParams struct {
	SsApiKey           string `json:"ss-api-key"`
	SsRequestSignature string `json:"ss-request-signature"`
	SsRequestTimestamp string `json:"ss-request-timestamp"`
}

// DeletePackagePackageIdDirectoryDirectoryIdParams defines parameters for DeletePackagePackageIdDirectoryDirectoryId.
type DeletePackagePackageIdDirectoryDirectoryIdParams struct {
	SsApiKey           string `json:"ss-api-key"`
	SsRequestSignature string `json:"ss-request-signature"`
	SsRequestTimestamp string `json:"ss-request-timestamp"`
}

// GetPackagePackageIdDirectoryDirectoryIdFileFileIdParams defines parameters for GetPackagePackageIdDirectoryDirectoryIdFileFileId.
type GetPackagePackageIdDirectoryDirectoryIdFileFileIdParams struct {
	SsApiKey           string `json:"ss-api-key"`
	SsRequestSignature string `json:"ss-request-signature"`
	SsRequestTimestamp string `json:"ss-request-timestamp"`
}

// DeletePackagePackageIdDirectoryDirectoryIdFileFileIdParams defines parameters for DeletePackagePackageIdDirectoryDirectoryIdFileFileId.
type DeletePackagePackageIdDirectoryDirectoryIdFileFileIdParams struct {
	SsApiKey           string `json:"ss-api-key"`
	SsRequestSignature string `json:"ss-request-signature"`
	SsRequestTimestamp string `json:"ss-request-timestamp"`
}

// PostPackagePackageIdDirectoryDirectoryIdFileFileIdParams defines parameters for PostPackagePackageIdDirectoryDirectoryIdFileFileId.
type PostPackagePackageIdDirectoryDirectoryIdFileFileIdParams struct {
	SsApiKey           string `json:"ss-api-key"`
	SsRequestSignature string `json:"ss-request-signature"`
	SsRequestTimestamp string `json:"ss-request-timestamp"`
}

// PostPackagePackageIdDirectoryDirectoryIdFileFileIdDownloadUrlsJSONBody defines parameters for PostPackagePackageIdDirectoryDirectoryIdFileFileIdDownloadUrls.
type PostPackagePackageIdDirectoryDirectoryIdFileFileIdDownloadUrlsJSONBody = GetDownloadUrlsRequest

// PostPackagePackageIdDirectoryDirectoryIdFileFileIdDownloadUrlsParams defines parameters for PostPackagePackageIdDirectoryDirectoryIdFileFileIdDownloadUrls.
type PostPackagePackageIdDirectoryDirectoryIdFileFileIdDownloadUrlsParams struct {
	SsApiKey           string `json:"ss-api-key"`
	SsRequestSignature string `json:"ss-request-signature"`
	SsRequestTimestamp string `json:"ss-request-timestamp"`
}

// PutPackagePackageIdDirectoryDirectoryIdSubdirectoryJSONBody defines parameters for PutPackagePackageIdDirectoryDirectoryIdSubdirectory.
type PutPackagePackageIdDirectoryDirectoryIdSubdirectoryJSONBody = CreateWorkspaceSubdirectoryRequest

// PutPackagePackageIdDirectoryDirectoryIdSubdirectoryParams defines parameters for PutPackagePackageIdDirectoryDirectoryIdSubdirectory.
type PutPackagePackageIdDirectoryDirectoryIdSubdirectoryParams struct {
	SsApiKey           string `json:"ss-api-key"`
	SsRequestSignature string `json:"ss-request-signature"`
	SsRequestTimestamp string `json:"ss-request-timestamp"`
	ContentType        string `json:"content-type"`
}

// CreateFileJSONBody defines parameters for CreateFile.
type CreateFileJSONBody = CreateFileRequest

// CreateFileParams defines parameters for CreateFile.
type CreateFileParams struct {
	SsApiKey           string `json:"ss-api-key"`
	SsRequestTimestamp string `json:"ss-request-timestamp"`
	SsRequestSignature string `json:"ss-request-signature"`
}

// DeletePackagePackageIdFileFileIdParams defines parameters for DeletePackagePackageIdFileFileId.
type DeletePackagePackageIdFileFileIdParams struct {
	SsApiKey           string `json:"ss-api-key"`
	SsRequestSignature string `json:"ss-request-signature"`
	SsRequestTimestamp string `json:"ss-request-timestamp"`
}

// GetPackagePackageIdFileFileIdParams defines parameters for GetPackagePackageIdFileFileId.
type GetPackagePackageIdFileFileIdParams struct {
	SsApiKey           string `json:"ss-api-key"`
	SsRequestSignature string `json:"ss-request-signature"`
	SsRequestTimestamp string `json:"ss-request-timestamp"`
}

// PostPackagePackageIdFileFileIdCopyJSONBody defines parameters for PostPackagePackageIdFileFileIdCopy.
type PostPackagePackageIdFileFileIdCopyJSONBody = CopyFileRequest

// PostPackagePackageIdFileFileIdCopyParams defines parameters for PostPackagePackageIdFileFileIdCopy.
type PostPackagePackageIdFileFileIdCopyParams struct {
	SsApiKey           string `json:"ss-api-key"`
	SsRequestSignature string `json:"ss-request-signature"`
	SsRequestTimestamp string `json:"ss-request-timestamp"`
	ContentType        string `json:"content-type"`
}

// PostPackagePackageIdFileFileIdDownloadUrlsJSONBody defines parameters for PostPackagePackageIdFileFileIdDownloadUrls.
type PostPackagePackageIdFileFileIdDownloadUrlsJSONBody = GetDownloadUrlsRequest

// PostPackagePackageIdFileFileIdDownloadUrlsParams defines parameters for PostPackagePackageIdFileFileIdDownloadUrls.
type PostPackagePackageIdFileFileIdDownloadUrlsParams struct {
	SsApiKey           string `json:"ss-api-key"`
	SsRequestSignature string `json:"ss-request-signature"`
	SsRequestTimestamp string `json:"ss-request-timestamp"`
}

// UploadCompleteJSONBody defines parameters for UploadComplete.
type UploadCompleteJSONBody = UploadCompletedRequest

// UploadCompleteParams defines parameters for UploadComplete.
type UploadCompleteParams struct {
	SsApiKey           string `json:"ss-api-key"`
	SsRequestTimestamp string `json:"ss-request-timestamp"`
	SsRequestSignature string `json:"ss-request-signature"`
}

// GetUploadUrlsJSONBody defines parameters for GetUploadUrls.
type GetUploadUrlsJSONBody = GetUploadUrlsRequest

// GetUploadUrlsParams defines parameters for GetUploadUrls.
type GetUploadUrlsParams struct {
	SsApiKey           string `json:"ss-api-key"`
	SsRequestTimestamp string `json:"ss-request-timestamp"`
	SsRequestSignature string `json:"ss-request-signature"`
}

// FinalizePackageJSONBody defines parameters for FinalizePackage.
type FinalizePackageJSONBody = FinalizePackageRequest

// FinalizePackageParams defines parameters for FinalizePackage.
type FinalizePackageParams struct {
	SsApiKey           string `json:"ss-api-key"`
	SsRequestTimestamp string `json:"ss-request-timestamp"`
	SsRequestSignature string `json:"ss-request-signature"`
}

// DeletePackagePackageIdGroupGroupIdParams defines parameters for DeletePackagePackageIdGroupGroupId.
type DeletePackagePackageIdGroupGroupIdParams struct {
	SsApiKey           string `json:"ss-api-key"`
	SsRequestSignature string `json:"ss-request-signature"`
	SsRequestTimestamp string `json:"ss-request-timestamp"`
}

// PutPackagePackageIdGroupGroupIdParams defines parameters for PutPackagePackageIdGroupGroupId.
type PutPackagePackageIdGroupGroupIdParams struct {
	SsApiKey           string `json:"ss-api-key"`
	SsRequestSignature string `json:"ss-request-signature"`
	SsRequestTimestamp string `json:"ss-request-timestamp"`
}

// GetPackagePackageIdLinkPublicKeyIdParams defines parameters for GetPackagePackageIdLinkPublicKeyId.
type GetPackagePackageIdLinkPublicKeyIdParams struct {
	SsApiKey           string `json:"ss-api-key"`
	SsRequestTimestamp string `json:"ss-request-timestamp"`
	SsRequestSignature string `json:"ss-request-signature"`
}

// PutPackagePackageIdLinkPublicKeyIdParams defines parameters for PutPackagePackageIdLinkPublicKeyId.
type PutPackagePackageIdLinkPublicKeyIdParams struct {
	SsApiKey           string `json:"ss-api-key"`
	SsRequestTimestamp string `json:"ss-request-timestamp"`
	SsRequestSignature string `json:"ss-request-signature"`
}

// UploadEncryptedMessageJSONBody defines parameters for UploadEncryptedMessage.
type UploadEncryptedMessageJSONBody = UploadEncryptedMessageRequest

// UploadEncryptedMessageParams defines parameters for UploadEncryptedMessage.
type UploadEncryptedMessageParams struct {
	SsApiKey           string `json:"ss-api-key"`
	SsRequestTimestamp string `json:"ss-request-timestamp"`
	SsRequestSignature string `json:"ss-request-signature"`
}

// GetPackagePackageIdMessageChecksumParams defines parameters for GetPackagePackageIdMessageChecksum.
type GetPackagePackageIdMessageChecksumParams struct {
	SsApiKey           string `json:"ss-api-key"`
	SsRequestSignature string `json:"ss-request-signature"`
	SsRequestTimestamp string `json:"ss-request-timestamp"`
}

// PostPackagePackageIdMoveSourcedirectoryIdTargetdirectoryIdParams defines parameters for PostPackagePackageIdMoveSourcedirectoryIdTargetdirectoryId.
type PostPackagePackageIdMoveSourcedirectoryIdTargetdirectoryIdParams struct {
	SsApiKey           string `json:"ss-api-key"`
	SsRequestSignature string `json:"ss-request-signature"`
	SsRequestTimestamp string `json:"ss-request-timestamp"`
}

// GetPackagePackageIdPublicKeysParams defines parameters for GetPackagePackageIdPublicKeys.
type GetPackagePackageIdPublicKeysParams struct {
	SsApiKey           string `json:"ss-api-key"`
	SsRequestTimestamp string `json:"ss-request-timestamp"`
	SsRequestSignature string `json:"ss-request-signature"`
}

// AddRecipientJSONBody defines parameters for AddRecipient.
type AddRecipientJSONBody = AddRecipientRequest

// AddRecipientParams defines parameters for AddRecipient.
type AddRecipientParams struct {
	SsApiKey           string `json:"ss-api-key"`
	SsRequestTimestamp string `json:"ss-request-timestamp"`
	SsRequestSignature string `json:"ss-request-signature"`
}

// DeletePackagePackageIdRecipientRecipientIdParams defines parameters for DeletePackagePackageIdRecipientRecipientId.
type DeletePackagePackageIdRecipientRecipientIdParams struct {
	SsApiKey           string `json:"ss-api-key"`
	SsRequestSignature string `json:"ss-request-signature"`
	SsRequestTimestamp string `json:"ss-request-timestamp"`
}

// GetPackagePackageIdRecipientRecipientIdParams defines parameters for GetPackagePackageIdRecipientRecipientId.
type GetPackagePackageIdRecipientRecipientIdParams struct {
	SsApiKey           string `json:"ss-api-key"`
	SsRequestSignature string `json:"ss-request-signature"`
	SsRequestTimestamp string `json:"ss-request-timestamp"`
}

// PostPackagePackageIdRecipientRecipientIdJSONBody defines parameters for PostPackagePackageIdRecipientRecipientId.
type PostPackagePackageIdRecipientRecipientIdJSONBody = UpdateRecipientRequest

// PostPackagePackageIdRecipientRecipientIdParams defines parameters for PostPackagePackageIdRecipientRecipientId.
type PostPackagePackageIdRecipientRecipientIdParams struct {
	SsApiKey           string `json:"ss-api-key"`
	SsRequestSignature string `json:"ss-request-signature"`
	SsRequestTimestamp string `json:"ss-request-timestamp"`
}

// PutPackagePackageIdRecipientsJSONBody defines parameters for PutPackagePackageIdRecipients.
type PutPackagePackageIdRecipientsJSONBody = AddRecipientsRequest

// PutPackagePackageIdRecipientsParams defines parameters for PutPackagePackageIdRecipients.
type PutPackagePackageIdRecipientsParams struct {
	SsApiKey           string `json:"ss-api-key"`
	SsRequestSignature string `json:"ss-request-signature"`
	SsRequestTimestamp string `json:"ss-request-timestamp"`
	ContentType        string `json:"content-type"`
}

// DeletePackagePackageIdTempParams defines parameters for DeletePackagePackageIdTemp.
type DeletePackagePackageIdTempParams struct {
	SsApiKey           string `json:"ss-api-key"`
	SsRequestTimestamp string `json:"ss-request-timestamp"`
	SsRequestSignature string `json:"ss-request-signature"`
}

// GetPackagePackageIdRecipientIdPublicKeysParams defines parameters for GetPackagePackageIdRecipientIdPublicKeys.
type GetPackagePackageIdRecipientIdPublicKeysParams struct {
	SsApiKey           string `json:"ss-api-key"`
	SsRequestSignature string `json:"ss-request-signature"`
	SsRequestTimestamp string `json:"ss-request-timestamp"`
	ContentType        string `json:"content-type"`
}

// PutPublicKeyJSONBody defines parameters for PutPublicKey.
type PutPublicKeyJSONBody = AddPublicKeyRequest

// PutPublicKeyParams defines parameters for PutPublicKey.
type PutPublicKeyParams struct {
	SsApiKey           string `json:"ss-api-key"`
	SsRequestSignature string `json:"ss-request-signature"`
	SsRequestTimestamp string `json:"ss-request-timestamp"`
	ContentType        string `json:"content-type"`
}

// DeletePublicKeyPublicKeyIdParams defines parameters for DeletePublicKeyPublicKeyId.
type DeletePublicKeyPublicKeyIdParams struct {
	SsApiKey           string `json:"ss-api-key"`
	SsRequestSignature string `json:"ss-request-signature"`
	SsRequestTimestamp string `json:"ss-request-timestamp"`
	ContentType        string `json:"content-type"`
}

// GetPublicKeyPublicKeyIdParams defines parameters for GetPublicKeyPublicKeyId.
type GetPublicKeyPublicKeyIdParams struct {
	SsApiKey           string `json:"ss-api-key"`
	SsRequestSignature string `json:"ss-request-signature"`
	SsRequestTimestamp string `json:"ss-request-timestamp"`
	ContentType        string `json:"content-type"`
}

// GetRecipientHistoryRecipientEmailParams defines parameters for GetRecipientHistoryRecipientEmail.
type GetRecipientHistoryRecipientEmailParams struct {
	SsApiKey           string `json:"ss-api-key"`
	SsRequestSignature string `json:"ss-request-signature"`
	SsRequestTimestamp string `json:"ss-request-timestamp"`
	ContentType        string `json:"content-type"`
}

// GetSyncPublicKeyIdParams defines parameters for GetSyncPublicKeyId.
type GetSyncPublicKeyIdParams struct {
	SsApiKey           string `json:"ss-api-key"`
	SsRequestSignature string `json:"ss-request-signature"`
	SsRequestTimestamp string `json:"ss-request-timestamp"`
	ContentType        string `json:"content-type"`
}

// GetUserParams defines parameters for GetUser.
type GetUserParams struct {
	SsApiKey           string `json:"ss-api-key"`
	SsRequestSignature string `json:"ss-request-signature"`
	SsRequestTimestamp string `json:"ss-request-timestamp"`
}

// DeleteUserDropzoneRecipientsParams defines parameters for DeleteUserDropzoneRecipients.
type DeleteUserDropzoneRecipientsParams struct {
	SsApiKey           string `json:"ss-api-key"`
	SsRequestSignature string `json:"ss-request-signature"`
	SsRequestTimestamp string `json:"ss-request-timestamp"`
	ContentType        string `json:"content-type"`
}

// GetUserDropzoneRecipientsParams defines parameters for GetUserDropzoneRecipients.
type GetUserDropzoneRecipientsParams struct {
	SsApiKey           string `json:"ss-api-key"`
	SsRequestSignature string `json:"ss-request-signature"`
	SsRequestTimestamp string `json:"ss-request-timestamp"`
	ContentType        string `json:"content-type"`
}

// PutUserDropzoneRecipientsJSONBody defines parameters for PutUserDropzoneRecipients.
type PutUserDropzoneRecipientsJSONBody = AddRecipientsRequest

// PutUserDropzoneRecipientsParams defines parameters for PutUserDropzoneRecipients.
type PutUserDropzoneRecipientsParams struct {
	SsApiKey           string `json:"ss-api-key"`
	SsRequestSignature string `json:"ss-request-signature"`
	SsRequestTimestamp string `json:"ss-request-timestamp"`
	ContentType        string `json:"content-type"`
}

// GetUserGroupsParams defines parameters for GetUserGroups.
type GetUserGroupsParams struct {
	SsApiKey           string `json:"ss-api-key"`
	SsRequestSignature string `json:"ss-request-signature"`
	SsRequestTimestamp string `json:"ss-request-timestamp"`
}

// PostUserUserIdDropzoneConfigJSONBody defines parameters for PostUserUserIdDropzoneConfig.
type PostUserUserIdDropzoneConfigJSONBody = UpdateDropzoneRequest

// PostUserUserIdDropzoneConfigParams defines parameters for PostUserUserIdDropzoneConfig.
type PostUserUserIdDropzoneConfigParams struct {
	SsApiKey           string `json:"ss-api-key"`
	SsRequestSignature string `json:"ss-request-signature"`
	SsRequestTimestamp string `json:"ss-request-timestamp"`
	ContentType        string `json:"content-type"`
}

// PutGroupJSONRequestBody defines body for PutGroup for application/json ContentType.
type PutGroupJSONRequestBody = PutGroupJSONBody

// PutGroupGroupIdUserJSONRequestBody defines body for PutGroupGroupIdUser for application/json ContentType.
type PutGroupGroupIdUserJSONRequestBody = PutGroupGroupIdUserJSONBody

// CreatePackageJSONRequestBody defines body for CreatePackage for application/json ContentType.
type CreatePackageJSONRequestBody = CreatePackageJSONBody

// GetOrganizationPackagesJSONRequestBody defines body for GetOrganizationPackages for application/json ContentType.
type GetOrganizationPackagesJSONRequestBody = GetOrganizationPackagesJSONBody

// PostPackagePackageIdJSONRequestBody defines body for PostPackagePackageId for application/json ContentType.
type PostPackagePackageIdJSONRequestBody = PostPackagePackageIdJSONBody

// PostPackagePackageIdDirectoryDirectoryIdJSONRequestBody defines body for PostPackagePackageIdDirectoryDirectoryId for application/json ContentType.
type PostPackagePackageIdDirectoryDirectoryIdJSONRequestBody = PostPackagePackageIdDirectoryDirectoryIdJSONBody

// PostPackagePackageIdDirectoryDirectoryIdFileFileIdDownloadUrlsJSONRequestBody defines body for PostPackagePackageIdDirectoryDirectoryIdFileFileIdDownloadUrls for application/json ContentType.
type PostPackagePackageIdDirectoryDirectoryIdFileFileIdDownloadUrlsJSONRequestBody = PostPackagePackageIdDirectoryDirectoryIdFileFileIdDownloadUrlsJSONBody

// PutPackagePackageIdDirectoryDirectoryIdSubdirectoryJSONRequestBody defines body for PutPackagePackageIdDirectoryDirectoryIdSubdirectory for application/json ContentType.
type PutPackagePackageIdDirectoryDirectoryIdSubdirectoryJSONRequestBody = PutPackagePackageIdDirectoryDirectoryIdSubdirectoryJSONBody

// CreateFileJSONRequestBody defines body for CreateFile for application/json ContentType.
type CreateFileJSONRequestBody = CreateFileJSONBody

// PostPackagePackageIdFileFileIdCopyJSONRequestBody defines body for PostPackagePackageIdFileFileIdCopy for application/json ContentType.
type PostPackagePackageIdFileFileIdCopyJSONRequestBody = PostPackagePackageIdFileFileIdCopyJSONBody

// PostPackagePackageIdFileFileIdDownloadUrlsJSONRequestBody defines body for PostPackagePackageIdFileFileIdDownloadUrls for application/json ContentType.
type PostPackagePackageIdFileFileIdDownloadUrlsJSONRequestBody = PostPackagePackageIdFileFileIdDownloadUrlsJSONBody

// UploadCompleteJSONRequestBody defines body for UploadComplete for application/json ContentType.
type UploadCompleteJSONRequestBody = UploadCompleteJSONBody

// GetUploadUrlsJSONRequestBody defines body for GetUploadUrls for application/json ContentType.
type GetUploadUrlsJSONRequestBody = GetUploadUrlsJSONBody

// FinalizePackageJSONRequestBody defines body for FinalizePackage for application/json ContentType.
type FinalizePackageJSONRequestBody = FinalizePackageJSONBody

// UploadEncryptedMessageJSONRequestBody defines body for UploadEncryptedMessage for application/json ContentType.
type UploadEncryptedMessageJSONRequestBody = UploadEncryptedMessageJSONBody

// AddRecipientJSONRequestBody defines body for AddRecipient for application/json ContentType.
type AddRecipientJSONRequestBody = AddRecipientJSONBody

// PostPackagePackageIdRecipientRecipientIdJSONRequestBody defines body for PostPackagePackageIdRecipientRecipientId for application/json ContentType.
type PostPackagePackageIdRecipientRecipientIdJSONRequestBody = PostPackagePackageIdRecipientRecipientIdJSONBody

// PutPackagePackageIdRecipientsJSONRequestBody defines body for PutPackagePackageIdRecipients for application/json ContentType.
type PutPackagePackageIdRecipientsJSONRequestBody = PutPackagePackageIdRecipientsJSONBody

// PutPublicKeyJSONRequestBody defines body for PutPublicKey for application/json ContentType.
type PutPublicKeyJSONRequestBody = PutPublicKeyJSONBody

// PutUserDropzoneRecipientsJSONRequestBody defines body for PutUserDropzoneRecipients for application/json ContentType.
type PutUserDropzoneRecipientsJSONRequestBody = PutUserDropzoneRecipientsJSONBody

// PostUserUserIdDropzoneConfigJSONRequestBody defines body for PostUserUserIdDropzoneConfig for application/json ContentType.
type PostUserUserIdDropzoneConfigJSONRequestBody = PostUserUserIdDropzoneConfigJSONBody
