# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yb/util/proto_container_test.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='yb/util/proto_container_test.proto',
  package='yb',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\"yb/util/proto_container_test.proto\x12\x02yb\"A\n\x14ProtoContainerTestPB\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\x05\x12\x0c\n\x04note\x18\x03 \x01(\t\"$\n\x14TestStringRequiredPB\x12\x0c\n\x04text\x18\x01 \x02(\t\"$\n\x14TestStringRepeatedPB\x12\x0c\n\x04text\x18\x01 \x03(\t*\'\n\nTestPBEnum\x12\x07\n\x03\x46OO\x10\x01\x12\x07\n\x03\x42\x41R\x10\x02\x12\x07\n\x03\x42\x41Z\x10\x03'
)

_TESTPBENUM = _descriptor.EnumDescriptor(
  name='TestPBEnum',
  full_name='yb.TestPBEnum',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FOO', index=0, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BAR', index=1, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BAZ', index=2, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=185,
  serialized_end=224,
)
_sym_db.RegisterEnumDescriptor(_TESTPBENUM)

TestPBEnum = enum_type_wrapper.EnumTypeWrapper(_TESTPBENUM)
FOO = 1
BAR = 2
BAZ = 3



_PROTOCONTAINERTESTPB = _descriptor.Descriptor(
  name='ProtoContainerTestPB',
  full_name='yb.ProtoContainerTestPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='yb.ProtoContainerTestPB.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='yb.ProtoContainerTestPB.value', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='note', full_name='yb.ProtoContainerTestPB.note', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=107,
)


_TESTSTRINGREQUIREDPB = _descriptor.Descriptor(
  name='TestStringRequiredPB',
  full_name='yb.TestStringRequiredPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='yb.TestStringRequiredPB.text', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=145,
)


_TESTSTRINGREPEATEDPB = _descriptor.Descriptor(
  name='TestStringRepeatedPB',
  full_name='yb.TestStringRepeatedPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='yb.TestStringRepeatedPB.text', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=183,
)

DESCRIPTOR.message_types_by_name['ProtoContainerTestPB'] = _PROTOCONTAINERTESTPB
DESCRIPTOR.message_types_by_name['TestStringRequiredPB'] = _TESTSTRINGREQUIREDPB
DESCRIPTOR.message_types_by_name['TestStringRepeatedPB'] = _TESTSTRINGREPEATEDPB
DESCRIPTOR.enum_types_by_name['TestPBEnum'] = _TESTPBENUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProtoContainerTestPB = _reflection.GeneratedProtocolMessageType('ProtoContainerTestPB', (_message.Message,), {
  'DESCRIPTOR' : _PROTOCONTAINERTESTPB,
  '__module__' : 'yb.util.proto_container_test_pb2'
  # @@protoc_insertion_point(class_scope:yb.ProtoContainerTestPB)
  })
_sym_db.RegisterMessage(ProtoContainerTestPB)

TestStringRequiredPB = _reflection.GeneratedProtocolMessageType('TestStringRequiredPB', (_message.Message,), {
  'DESCRIPTOR' : _TESTSTRINGREQUIREDPB,
  '__module__' : 'yb.util.proto_container_test_pb2'
  # @@protoc_insertion_point(class_scope:yb.TestStringRequiredPB)
  })
_sym_db.RegisterMessage(TestStringRequiredPB)

TestStringRepeatedPB = _reflection.GeneratedProtocolMessageType('TestStringRepeatedPB', (_message.Message,), {
  'DESCRIPTOR' : _TESTSTRINGREPEATEDPB,
  '__module__' : 'yb.util.proto_container_test_pb2'
  # @@protoc_insertion_point(class_scope:yb.TestStringRepeatedPB)
  })
_sym_db.RegisterMessage(TestStringRepeatedPB)


# @@protoc_insertion_point(module_scope)
