# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yb/util/proto_container_test3.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from yb.util import proto_container_test_pb2 as yb_dot_util_dot_proto__container__test__pb2
from yb.util import proto_container_test2_pb2 as yb_dot_util_dot_proto__container__test2__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='yb/util/proto_container_test3.proto',
  package='yb',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n#yb/util/proto_container_test3.proto\x12\x02yb\x1a\"yb/util/proto_container_test.proto\x1a#yb/util/proto_container_test2.proto\"t\n\x15ProtoContainerTest3PB\x12,\n\nrecord_one\x18\x01 \x02(\x0b\x32\x18.yb.ProtoContainerTestPB\x12-\n\nrecord_two\x18\x02 \x02(\x0b\x32\x19.yb.ProtoContainerTest2PB'
  ,
  dependencies=[yb_dot_util_dot_proto__container__test__pb2.DESCRIPTOR,yb_dot_util_dot_proto__container__test2__pb2.DESCRIPTOR,])




_PROTOCONTAINERTEST3PB = _descriptor.Descriptor(
  name='ProtoContainerTest3PB',
  full_name='yb.ProtoContainerTest3PB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='record_one', full_name='yb.ProtoContainerTest3PB.record_one', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='record_two', full_name='yb.ProtoContainerTest3PB.record_two', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=232,
)

_PROTOCONTAINERTEST3PB.fields_by_name['record_one'].message_type = yb_dot_util_dot_proto__container__test__pb2._PROTOCONTAINERTESTPB
_PROTOCONTAINERTEST3PB.fields_by_name['record_two'].message_type = yb_dot_util_dot_proto__container__test2__pb2._PROTOCONTAINERTEST2PB
DESCRIPTOR.message_types_by_name['ProtoContainerTest3PB'] = _PROTOCONTAINERTEST3PB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProtoContainerTest3PB = _reflection.GeneratedProtocolMessageType('ProtoContainerTest3PB', (_message.Message,), {
  'DESCRIPTOR' : _PROTOCONTAINERTEST3PB,
  '__module__' : 'yb.util.proto_container_test3_pb2'
  # @@protoc_insertion_point(class_scope:yb.ProtoContainerTest3PB)
  })
_sym_db.RegisterMessage(ProtoContainerTest3PB)


# @@protoc_insertion_point(module_scope)
