//
//Copyright © 2021 Yugabyte Support
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: yugatool/healthcheck/tablet.proto

package healthcheck

import (
	consensus "github.com/yugabyte/yb-tools/yugatool/api/yb/consensus"
	master "github.com/yugabyte/yb-tools/yugatool/api/yb/master"
	util "github.com/yugabyte/yb-tools/yugatool/api/yb/util"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TabletReportPB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tablet          *string                       `protobuf:"bytes,1,req,name=tablet" json:"tablet,omitempty"`
	TabletLocations *master.TabletLocationsPB     `protobuf:"bytes,2,req,name=tablet_locations,json=tabletLocations" json:"tablet_locations,omitempty"`
	ReplicaStates   []*TabletReportPBReplicaState `protobuf:"bytes,3,rep,name=replica_states,json=replicaStates" json:"replica_states,omitempty"` // TODO: should reimplemented to be a list of app status errors
	Errors          *TabletReportPBErrorlist      `protobuf:"bytes,6,opt,name=errors" json:"errors,omitempty"`
}

func (x *TabletReportPB) Reset() {
	*x = TabletReportPB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yugatool_healthcheck_tablet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TabletReportPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TabletReportPB) ProtoMessage() {}

func (x *TabletReportPB) ProtoReflect() protoreflect.Message {
	mi := &file_yugatool_healthcheck_tablet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TabletReportPB.ProtoReflect.Descriptor instead.
func (*TabletReportPB) Descriptor() ([]byte, []int) {
	return file_yugatool_healthcheck_tablet_proto_rawDescGZIP(), []int{0}
}

func (x *TabletReportPB) GetTablet() string {
	if x != nil && x.Tablet != nil {
		return *x.Tablet
	}
	return ""
}

func (x *TabletReportPB) GetTabletLocations() *master.TabletLocationsPB {
	if x != nil {
		return x.TabletLocations
	}
	return nil
}

func (x *TabletReportPB) GetReplicaStates() []*TabletReportPBReplicaState {
	if x != nil {
		return x.ReplicaStates
	}
	return nil
}

func (x *TabletReportPB) GetErrors() *TabletReportPBErrorlist {
	if x != nil {
		return x.Errors
	}
	return nil
}

type TableReportPB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableInfo *master.ListTablesResponsePB_TableInfo `protobuf:"bytes,1,req,name=table_info,json=tableInfo" json:"table_info,omitempty"`
	Tablets   []*TabletReportPB                      `protobuf:"bytes,2,rep,name=tablets" json:"tablets,omitempty"`
}

func (x *TableReportPB) Reset() {
	*x = TableReportPB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yugatool_healthcheck_tablet_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TableReportPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableReportPB) ProtoMessage() {}

func (x *TableReportPB) ProtoReflect() protoreflect.Message {
	mi := &file_yugatool_healthcheck_tablet_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableReportPB.ProtoReflect.Descriptor instead.
func (*TableReportPB) Descriptor() ([]byte, []int) {
	return file_yugatool_healthcheck_tablet_proto_rawDescGZIP(), []int{1}
}

func (x *TableReportPB) GetTableInfo() *master.ListTablesResponsePB_TableInfo {
	if x != nil {
		return x.TableInfo
	}
	return nil
}

func (x *TableReportPB) GetTablets() []*TabletReportPB {
	if x != nil {
		return x.Tablets
	}
	return nil
}

type TabletReportPBReplicaState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid           []byte                                 `protobuf:"bytes,1,req,name=uuid" json:"uuid,omitempty"`
	ConsensusState *consensus.GetConsensusStateResponsePB `protobuf:"bytes,2,req,name=consensus_state,json=consensusState" json:"consensus_state,omitempty"`
	Opid           *util.OpIdPB                           `protobuf:"bytes,3,opt,name=opid" json:"opid,omitempty"`
}

func (x *TabletReportPBReplicaState) Reset() {
	*x = TabletReportPBReplicaState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yugatool_healthcheck_tablet_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TabletReportPBReplicaState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TabletReportPBReplicaState) ProtoMessage() {}

func (x *TabletReportPBReplicaState) ProtoReflect() protoreflect.Message {
	mi := &file_yugatool_healthcheck_tablet_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TabletReportPBReplicaState.ProtoReflect.Descriptor instead.
func (*TabletReportPBReplicaState) Descriptor() ([]byte, []int) {
	return file_yugatool_healthcheck_tablet_proto_rawDescGZIP(), []int{0, 0}
}

func (x *TabletReportPBReplicaState) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *TabletReportPBReplicaState) GetConsensusState() *consensus.GetConsensusStateResponsePB {
	if x != nil {
		return x.ConsensusState
	}
	return nil
}

func (x *TabletReportPBReplicaState) GetOpid() *util.OpIdPB {
	if x != nil {
		return x.Opid
	}
	return nil
}

type TabletReportPBErrorlist struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MissingLeader *TabletReportPBErrorlistMissingLeaderError `protobuf:"bytes,1,opt,name=missing_leader,json=missingLeader" json:"missing_leader,omitempty"`
}

func (x *TabletReportPBErrorlist) Reset() {
	*x = TabletReportPBErrorlist{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yugatool_healthcheck_tablet_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TabletReportPBErrorlist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TabletReportPBErrorlist) ProtoMessage() {}

func (x *TabletReportPBErrorlist) ProtoReflect() protoreflect.Message {
	mi := &file_yugatool_healthcheck_tablet_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TabletReportPBErrorlist.ProtoReflect.Descriptor instead.
func (*TabletReportPBErrorlist) Descriptor() ([]byte, []int) {
	return file_yugatool_healthcheck_tablet_proto_rawDescGZIP(), []int{0, 1}
}

func (x *TabletReportPBErrorlist) GetMissingLeader() *TabletReportPBErrorlistMissingLeaderError {
	if x != nil {
		return x.MissingLeader
	}
	return nil
}

type TabletReportPBErrorlistMissingLeaderError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BestLeaderUuid *string `protobuf:"bytes,1,req,name=best_leader_uuid,json=bestLeaderUuid" json:"best_leader_uuid,omitempty"`
}

func (x *TabletReportPBErrorlistMissingLeaderError) Reset() {
	*x = TabletReportPBErrorlistMissingLeaderError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yugatool_healthcheck_tablet_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TabletReportPBErrorlistMissingLeaderError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TabletReportPBErrorlistMissingLeaderError) ProtoMessage() {}

func (x *TabletReportPBErrorlistMissingLeaderError) ProtoReflect() protoreflect.Message {
	mi := &file_yugatool_healthcheck_tablet_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TabletReportPBErrorlistMissingLeaderError.ProtoReflect.Descriptor instead.
func (*TabletReportPBErrorlistMissingLeaderError) Descriptor() ([]byte, []int) {
	return file_yugatool_healthcheck_tablet_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *TabletReportPBErrorlistMissingLeaderError) GetBestLeaderUuid() string {
	if x != nil && x.BestLeaderUuid != nil {
		return *x.BestLeaderUuid
	}
	return ""
}

var File_yugatool_healthcheck_tablet_proto protoreflect.FileDescriptor

var file_yugatool_healthcheck_tablet_proto_rawDesc = []byte{
	0x0a, 0x21, 0x79, 0x75, 0x67, 0x61, 0x74, 0x6f, 0x6f, 0x6c, 0x2f, 0x68, 0x65, 0x61, 0x6c, 0x74,
	0x68, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x2f, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x14, 0x79, 0x75, 0x67, 0x61, 0x74, 0x6f, 0x6f, 0x6c, 0x2e, 0x68, 0x65,
	0x61, 0x6c, 0x74, 0x68, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x1a, 0x16, 0x79, 0x62, 0x2f, 0x6d, 0x61,
	0x73, 0x74, 0x65, 0x72, 0x2f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1c, 0x79, 0x62, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x2f,
	0x63, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x12, 0x79, 0x62, 0x2f, 0x75, 0x74, 0x69, 0x6c, 0x2f, 0x6f, 0x70, 0x69, 0x64, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xea, 0x04, 0x0a, 0x0e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x74, 0x52, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x50, 0x42, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x74,
	0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x74, 0x12, 0x47,
	0x0a, 0x10, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x74, 0x5f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x79, 0x62, 0x2e, 0x6d, 0x61,
	0x73, 0x74, 0x65, 0x72, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x50, 0x42, 0x52, 0x0f, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x74, 0x4c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x59, 0x0a, 0x0e, 0x72, 0x65, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x32, 0x2e, 0x79, 0x75, 0x67, 0x61, 0x74, 0x6f, 0x6f, 0x6c, 0x2e, 0x68, 0x65, 0x61, 0x6c, 0x74,
	0x68, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x74, 0x52, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x50, 0x42, 0x2e, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x5f, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x52, 0x0d, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x73, 0x12, 0x46, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x79, 0x75, 0x67, 0x61, 0x74, 0x6f, 0x6f, 0x6c, 0x2e, 0x68, 0x65,
	0x61, 0x6c, 0x74, 0x68, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x74,
	0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x50, 0x42, 0x2e, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x6c, 0x69,
	0x73, 0x74, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x1a, 0x97, 0x01, 0x0a, 0x0d, 0x72,
	0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64,
	0x12, 0x52, 0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x5f, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x79, 0x62, 0x2e, 0x63,
	0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x73,
	0x65, 0x6e, 0x73, 0x75, 0x73, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x50, 0x42, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x1e, 0x0a, 0x04, 0x6f, 0x70, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x79, 0x62, 0x2e, 0x4f, 0x70, 0x49, 0x64, 0x50, 0x42, 0x52, 0x04,
	0x6f, 0x70, 0x69, 0x64, 0x1a, 0xb9, 0x01, 0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x6c, 0x69,
	0x73, 0x74, 0x12, 0x6a, 0x0a, 0x0e, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x5f, 0x6c, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x43, 0x2e, 0x79, 0x75, 0x67,
	0x61, 0x74, 0x6f, 0x6f, 0x6c, 0x2e, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x63, 0x68, 0x65, 0x63,
	0x6b, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x50, 0x42,
	0x2e, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6e, 0x67, 0x5f, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x52,
	0x0d, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x1a, 0x40,
	0x0a, 0x14, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x5f, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x28, 0x0a, 0x10, 0x62, 0x65, 0x73, 0x74, 0x5f, 0x6c,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09,
	0x52, 0x0e, 0x62, 0x65, 0x73, 0x74, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64,
	0x22, 0x99, 0x01, 0x0a, 0x0d, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x50, 0x42, 0x12, 0x48, 0x0a, 0x0a, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f,
	0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x79, 0x62, 0x2e, 0x6d, 0x61, 0x73, 0x74,
	0x65, 0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x42, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x09, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x3e, 0x0a, 0x07,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e,
	0x79, 0x75, 0x67, 0x61, 0x74, 0x6f, 0x6f, 0x6c, 0x2e, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x63,
	0x68, 0x65, 0x63, 0x6b, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x50, 0x42, 0x52, 0x07, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x74, 0x73, 0x42, 0x1a, 0x0a, 0x18,
	0x6f, 0x72, 0x67, 0x2e, 0x79, 0x75, 0x67, 0x61, 0x74, 0x6f, 0x6f, 0x6c, 0x2e, 0x68, 0x65, 0x61,
	0x6c, 0x74, 0x68, 0x63, 0x68, 0x65, 0x63, 0x6b,
}

var (
	file_yugatool_healthcheck_tablet_proto_rawDescOnce sync.Once
	file_yugatool_healthcheck_tablet_proto_rawDescData = file_yugatool_healthcheck_tablet_proto_rawDesc
)

func file_yugatool_healthcheck_tablet_proto_rawDescGZIP() []byte {
	file_yugatool_healthcheck_tablet_proto_rawDescOnce.Do(func() {
		file_yugatool_healthcheck_tablet_proto_rawDescData = protoimpl.X.CompressGZIP(file_yugatool_healthcheck_tablet_proto_rawDescData)
	})
	return file_yugatool_healthcheck_tablet_proto_rawDescData
}

var file_yugatool_healthcheck_tablet_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_yugatool_healthcheck_tablet_proto_goTypes = []interface{}{
	(*TabletReportPB)(nil),                            // 0: yugatool.healthcheck.TabletReportPB
	(*TableReportPB)(nil),                             // 1: yugatool.healthcheck.TableReportPB
	(*TabletReportPBReplicaState)(nil),                // 2: yugatool.healthcheck.TabletReportPB.replica_state
	(*TabletReportPBErrorlist)(nil),                   // 3: yugatool.healthcheck.TabletReportPB.errorlist
	(*TabletReportPBErrorlistMissingLeaderError)(nil), // 4: yugatool.healthcheck.TabletReportPB.errorlist.missing_leader_error
	(*master.TabletLocationsPB)(nil),                  // 5: yb.master.TabletLocationsPB
	(*master.ListTablesResponsePB_TableInfo)(nil),     // 6: yb.master.ListTablesResponsePB.TableInfo
	(*consensus.GetConsensusStateResponsePB)(nil),     // 7: yb.consensus.GetConsensusStateResponsePB
	(*util.OpIdPB)(nil),                               // 8: yb.OpIdPB
}
var file_yugatool_healthcheck_tablet_proto_depIdxs = []int32{
	5, // 0: yugatool.healthcheck.TabletReportPB.tablet_locations:type_name -> yb.master.TabletLocationsPB
	2, // 1: yugatool.healthcheck.TabletReportPB.replica_states:type_name -> yugatool.healthcheck.TabletReportPB.replica_state
	3, // 2: yugatool.healthcheck.TabletReportPB.errors:type_name -> yugatool.healthcheck.TabletReportPB.errorlist
	6, // 3: yugatool.healthcheck.TableReportPB.table_info:type_name -> yb.master.ListTablesResponsePB.TableInfo
	0, // 4: yugatool.healthcheck.TableReportPB.tablets:type_name -> yugatool.healthcheck.TabletReportPB
	7, // 5: yugatool.healthcheck.TabletReportPB.replica_state.consensus_state:type_name -> yb.consensus.GetConsensusStateResponsePB
	8, // 6: yugatool.healthcheck.TabletReportPB.replica_state.opid:type_name -> yb.OpIdPB
	4, // 7: yugatool.healthcheck.TabletReportPB.errorlist.missing_leader:type_name -> yugatool.healthcheck.TabletReportPB.errorlist.missing_leader_error
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_yugatool_healthcheck_tablet_proto_init() }
func file_yugatool_healthcheck_tablet_proto_init() {
	if File_yugatool_healthcheck_tablet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_yugatool_healthcheck_tablet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TabletReportPB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yugatool_healthcheck_tablet_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TableReportPB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yugatool_healthcheck_tablet_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TabletReportPBReplicaState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yugatool_healthcheck_tablet_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TabletReportPBErrorlist); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yugatool_healthcheck_tablet_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TabletReportPBErrorlistMissingLeaderError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_yugatool_healthcheck_tablet_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_yugatool_healthcheck_tablet_proto_goTypes,
		DependencyIndexes: file_yugatool_healthcheck_tablet_proto_depIdxs,
		MessageInfos:      file_yugatool_healthcheck_tablet_proto_msgTypes,
	}.Build()
	File_yugatool_healthcheck_tablet_proto = out.File
	file_yugatool_healthcheck_tablet_proto_rawDesc = nil
	file_yugatool_healthcheck_tablet_proto_goTypes = nil
	file_yugatool_healthcheck_tablet_proto_depIdxs = nil
}
