# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yb/rpc/rpc_header.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='yb/rpc/rpc_header.proto',
  package='yb.rpc',
  syntax='proto2',
  serialized_options=b'\n\norg.yb.rpc',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17yb/rpc/rpc_header.proto\x12\x06yb.rpc\";\n\x0eRemoteMethodPB\x12\x14\n\x0cservice_name\x18\x01 \x02(\t\x12\x13\n\x0bmethod_name\x18\x02 \x02(\t\"g\n\rRequestHeader\x12\x0f\n\x07\x63\x61ll_id\x18\x01 \x02(\x05\x12-\n\rremote_method\x18\x02 \x01(\x0b\x32\x16.yb.rpc.RemoteMethodPB\x12\x16\n\x0etimeout_millis\x18\x03 \x01(\r\"S\n\x0eResponseHeader\x12\x0f\n\x07\x63\x61ll_id\x18\x01 \x02(\x05\x12\x17\n\x08is_error\x18\x02 \x01(\x08:\x05\x66\x61lse\x12\x17\n\x0fsidecar_offsets\x18\x03 \x03(\r\"\x10\n\x0e\x45mptyMessagePB\"\xfb\x02\n\rErrorStatusPB\x12\x0f\n\x07message\x18\x01 \x02(\t\x12\x32\n\x04\x63ode\x18\x02 \x01(\x0e\x32$.yb.rpc.ErrorStatusPB.RpcErrorCodePB\"\x9a\x02\n\x0eRpcErrorCodePB\x12\x11\n\rFATAL_UNKNOWN\x10\n\x12\x15\n\x11\x45RROR_APPLICATION\x10\x01\x12\x18\n\x14\x45RROR_NO_SUCH_METHOD\x10\x02\x12\x19\n\x15\x45RROR_NO_SUCH_SERVICE\x10\x03\x12\x19\n\x15\x45RROR_SERVER_TOO_BUSY\x10\x04\x12\x19\n\x15\x45RROR_INVALID_REQUEST\x10\x05\x12\x1e\n\x1a\x46\x41TAL_SERVER_SHUTTING_DOWN\x10\x0b\x12\x1f\n\x1b\x46\x41TAL_DESERIALIZING_REQUEST\x10\r\x12\x1a\n\x16\x46\x41TAL_VERSION_MISMATCH\x10\x0e\x12\x16\n\x12\x46\x41TAL_UNAUTHORIZED\x10\x0f*\x08\x08\x64\x10\x80\x80\x80\x80\x02\x42\x0c\n\norg.yb.rpc'
)



_ERRORSTATUSPB_RPCERRORCODEPB = _descriptor.EnumDescriptor(
  name='RpcErrorCodePB',
  full_name='yb.rpc.ErrorStatusPB.RpcErrorCodePB',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FATAL_UNKNOWN', index=0, number=10,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ERROR_APPLICATION', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ERROR_NO_SUCH_METHOD', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ERROR_NO_SUCH_SERVICE', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ERROR_SERVER_TOO_BUSY', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ERROR_INVALID_REQUEST', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FATAL_SERVER_SHUTTING_DOWN', index=6, number=11,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FATAL_DESERIALIZING_REQUEST', index=7, number=13,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FATAL_VERSION_MISMATCH', index=8, number=14,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FATAL_UNAUTHORIZED', index=9, number=15,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=392,
  serialized_end=674,
)
_sym_db.RegisterEnumDescriptor(_ERRORSTATUSPB_RPCERRORCODEPB)


_REMOTEMETHODPB = _descriptor.Descriptor(
  name='RemoteMethodPB',
  full_name='yb.rpc.RemoteMethodPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='service_name', full_name='yb.rpc.RemoteMethodPB.service_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='method_name', full_name='yb.rpc.RemoteMethodPB.method_name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=94,
)


_REQUESTHEADER = _descriptor.Descriptor(
  name='RequestHeader',
  full_name='yb.rpc.RequestHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='call_id', full_name='yb.rpc.RequestHeader.call_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='remote_method', full_name='yb.rpc.RequestHeader.remote_method', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timeout_millis', full_name='yb.rpc.RequestHeader.timeout_millis', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=199,
)


_RESPONSEHEADER = _descriptor.Descriptor(
  name='ResponseHeader',
  full_name='yb.rpc.ResponseHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='call_id', full_name='yb.rpc.ResponseHeader.call_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_error', full_name='yb.rpc.ResponseHeader.is_error', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sidecar_offsets', full_name='yb.rpc.ResponseHeader.sidecar_offsets', index=2,
      number=3, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=284,
)


_EMPTYMESSAGEPB = _descriptor.Descriptor(
  name='EmptyMessagePB',
  full_name='yb.rpc.EmptyMessagePB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=286,
  serialized_end=302,
)


_ERRORSTATUSPB = _descriptor.Descriptor(
  name='ErrorStatusPB',
  full_name='yb.rpc.ErrorStatusPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='yb.rpc.ErrorStatusPB.message', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='code', full_name='yb.rpc.ErrorStatusPB.code', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=10,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ERRORSTATUSPB_RPCERRORCODEPB,
  ],
  serialized_options=None,
  is_extendable=True,
  syntax='proto2',
  extension_ranges=[(100, 536870912), ],
  oneofs=[
  ],
  serialized_start=305,
  serialized_end=684,
)

_REQUESTHEADER.fields_by_name['remote_method'].message_type = _REMOTEMETHODPB
_ERRORSTATUSPB.fields_by_name['code'].enum_type = _ERRORSTATUSPB_RPCERRORCODEPB
_ERRORSTATUSPB_RPCERRORCODEPB.containing_type = _ERRORSTATUSPB
DESCRIPTOR.message_types_by_name['RemoteMethodPB'] = _REMOTEMETHODPB
DESCRIPTOR.message_types_by_name['RequestHeader'] = _REQUESTHEADER
DESCRIPTOR.message_types_by_name['ResponseHeader'] = _RESPONSEHEADER
DESCRIPTOR.message_types_by_name['EmptyMessagePB'] = _EMPTYMESSAGEPB
DESCRIPTOR.message_types_by_name['ErrorStatusPB'] = _ERRORSTATUSPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RemoteMethodPB = _reflection.GeneratedProtocolMessageType('RemoteMethodPB', (_message.Message,), {
  'DESCRIPTOR' : _REMOTEMETHODPB,
  '__module__' : 'yb.rpc.rpc_header_pb2'
  # @@protoc_insertion_point(class_scope:yb.rpc.RemoteMethodPB)
  })
_sym_db.RegisterMessage(RemoteMethodPB)

RequestHeader = _reflection.GeneratedProtocolMessageType('RequestHeader', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTHEADER,
  '__module__' : 'yb.rpc.rpc_header_pb2'
  # @@protoc_insertion_point(class_scope:yb.rpc.RequestHeader)
  })
_sym_db.RegisterMessage(RequestHeader)

ResponseHeader = _reflection.GeneratedProtocolMessageType('ResponseHeader', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEHEADER,
  '__module__' : 'yb.rpc.rpc_header_pb2'
  # @@protoc_insertion_point(class_scope:yb.rpc.ResponseHeader)
  })
_sym_db.RegisterMessage(ResponseHeader)

EmptyMessagePB = _reflection.GeneratedProtocolMessageType('EmptyMessagePB', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYMESSAGEPB,
  '__module__' : 'yb.rpc.rpc_header_pb2'
  # @@protoc_insertion_point(class_scope:yb.rpc.EmptyMessagePB)
  })
_sym_db.RegisterMessage(EmptyMessagePB)

ErrorStatusPB = _reflection.GeneratedProtocolMessageType('ErrorStatusPB', (_message.Message,), {
  'DESCRIPTOR' : _ERRORSTATUSPB,
  '__module__' : 'yb.rpc.rpc_header_pb2'
  # @@protoc_insertion_point(class_scope:yb.rpc.ErrorStatusPB)
  })
_sym_db.RegisterMessage(ErrorStatusPB)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
