# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yb/rocksdb/db/version_edit.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from yb.util import opid_pb2 as yb_dot_util_dot_opid__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='yb/rocksdb/db/version_edit.proto',
  package='rocksdb',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n yb/rocksdb/db/version_edit.proto\x12\x07rocksdb\x1a\x12yb/util/opid.proto\x1a\x19google/protobuf/any.proto\"3\n\rDeletedFilePB\x12\r\n\x05level\x18\x01 \x01(\r\x12\x13\n\x0b\x66ile_number\x18\x02 \x01(\x04\"0\n\x13UserBoundaryValuePB\x12\x0b\n\x03tag\x18\x01 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"\x8e\x01\n\x10\x42oundaryValuesPB\x12\x0b\n\x03key\x18\x01 \x01(\x0c\x12\r\n\x05seqno\x18\x02 \x01(\x04\x12+\n\ruser_frontier\x18\x04 \x01(\x0b\x32\x14.google.protobuf.Any\x12\x31\n\x0buser_values\x18\x03 \x03(\x0b\x32\x1c.rocksdb.UserBoundaryValuePB\"\x9f\x02\n\tNewFilePB\x12\r\n\x05level\x18\x01 \x01(\r\x12\x0e\n\x06number\x18\x02 \x01(\x04\x12\x17\n\x0ftotal_file_size\x18\x03 \x01(\x04\x12\x16\n\x0e\x62\x61se_file_size\x18\x04 \x01(\x04\x12+\n\x08smallest\x18\x05 \x01(\x0b\x32\x19.rocksdb.BoundaryValuesPB\x12*\n\x07largest\x18\x06 \x01(\x0b\x32\x19.rocksdb.BoundaryValuesPB\x12\x0f\n\x07path_id\x18\x07 \x01(\r\x12\x1d\n\x15marked_for_compaction\x18\x08 \x01(\x08\x12\'\n\x13obsolete_last_op_id\x18\t \x01(\x0b\x32\n.yb.OpIdPB\x12\x10\n\x08imported\x18\n \x01(\x08\"\x9d\x03\n\rVersionEditPB\x12\x12\n\ncomparator\x18\x01 \x01(\t\x12\x12\n\nlog_number\x18\x02 \x01(\x04\x12\x17\n\x0fprev_log_number\x18\x03 \x01(\x04\x12\x18\n\x10next_file_number\x18\x04 \x01(\x04\x12\x19\n\x11max_column_family\x18\x05 \x01(\r\x12\x15\n\rlast_sequence\x18\x06 \x01(\x04\x12-\n\rdeleted_files\x18\x07 \x03(\x0b\x32\x16.rocksdb.DeletedFilePB\x12%\n\tnew_files\x18\x08 \x03(\x0b\x32\x12.rocksdb.NewFilePB\x12\x15\n\rcolumn_family\x18\t \x01(\r\x12\x1a\n\x12\x63olumn_family_name\x18\n \x01(\t\x12\x1d\n\x15is_column_family_drop\x18\x0b \x01(\x08\x12\'\n\x13obsolete_last_op_id\x18\x0c \x01(\x0b\x32\n.yb.OpIdPB\x12.\n\x10\x66lushed_frontier\x18\r \x01(\x0b\x32\x14.google.protobuf.Any'
  ,
  dependencies=[yb_dot_util_dot_opid__pb2.DESCRIPTOR,google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])




_DELETEDFILEPB = _descriptor.Descriptor(
  name='DeletedFilePB',
  full_name='rocksdb.DeletedFilePB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='level', full_name='rocksdb.DeletedFilePB.level', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='file_number', full_name='rocksdb.DeletedFilePB.file_number', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=143,
)


_USERBOUNDARYVALUEPB = _descriptor.Descriptor(
  name='UserBoundaryValuePB',
  full_name='rocksdb.UserBoundaryValuePB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tag', full_name='rocksdb.UserBoundaryValuePB.tag', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='rocksdb.UserBoundaryValuePB.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=193,
)


_BOUNDARYVALUESPB = _descriptor.Descriptor(
  name='BoundaryValuesPB',
  full_name='rocksdb.BoundaryValuesPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='rocksdb.BoundaryValuesPB.key', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='seqno', full_name='rocksdb.BoundaryValuesPB.seqno', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_frontier', full_name='rocksdb.BoundaryValuesPB.user_frontier', index=2,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_values', full_name='rocksdb.BoundaryValuesPB.user_values', index=3,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=338,
)


_NEWFILEPB = _descriptor.Descriptor(
  name='NewFilePB',
  full_name='rocksdb.NewFilePB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='level', full_name='rocksdb.NewFilePB.level', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='number', full_name='rocksdb.NewFilePB.number', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_file_size', full_name='rocksdb.NewFilePB.total_file_size', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='base_file_size', full_name='rocksdb.NewFilePB.base_file_size', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='smallest', full_name='rocksdb.NewFilePB.smallest', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='largest', full_name='rocksdb.NewFilePB.largest', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='path_id', full_name='rocksdb.NewFilePB.path_id', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='marked_for_compaction', full_name='rocksdb.NewFilePB.marked_for_compaction', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='obsolete_last_op_id', full_name='rocksdb.NewFilePB.obsolete_last_op_id', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='imported', full_name='rocksdb.NewFilePB.imported', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=341,
  serialized_end=628,
)


_VERSIONEDITPB = _descriptor.Descriptor(
  name='VersionEditPB',
  full_name='rocksdb.VersionEditPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='comparator', full_name='rocksdb.VersionEditPB.comparator', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='log_number', full_name='rocksdb.VersionEditPB.log_number', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='prev_log_number', full_name='rocksdb.VersionEditPB.prev_log_number', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='next_file_number', full_name='rocksdb.VersionEditPB.next_file_number', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_column_family', full_name='rocksdb.VersionEditPB.max_column_family', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_sequence', full_name='rocksdb.VersionEditPB.last_sequence', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='deleted_files', full_name='rocksdb.VersionEditPB.deleted_files', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='new_files', full_name='rocksdb.VersionEditPB.new_files', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='column_family', full_name='rocksdb.VersionEditPB.column_family', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='column_family_name', full_name='rocksdb.VersionEditPB.column_family_name', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_column_family_drop', full_name='rocksdb.VersionEditPB.is_column_family_drop', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='obsolete_last_op_id', full_name='rocksdb.VersionEditPB.obsolete_last_op_id', index=11,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='flushed_frontier', full_name='rocksdb.VersionEditPB.flushed_frontier', index=12,
      number=13, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=631,
  serialized_end=1044,
)

_BOUNDARYVALUESPB.fields_by_name['user_frontier'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_BOUNDARYVALUESPB.fields_by_name['user_values'].message_type = _USERBOUNDARYVALUEPB
_NEWFILEPB.fields_by_name['smallest'].message_type = _BOUNDARYVALUESPB
_NEWFILEPB.fields_by_name['largest'].message_type = _BOUNDARYVALUESPB
_NEWFILEPB.fields_by_name['obsolete_last_op_id'].message_type = yb_dot_util_dot_opid__pb2._OPIDPB
_VERSIONEDITPB.fields_by_name['deleted_files'].message_type = _DELETEDFILEPB
_VERSIONEDITPB.fields_by_name['new_files'].message_type = _NEWFILEPB
_VERSIONEDITPB.fields_by_name['obsolete_last_op_id'].message_type = yb_dot_util_dot_opid__pb2._OPIDPB
_VERSIONEDITPB.fields_by_name['flushed_frontier'].message_type = google_dot_protobuf_dot_any__pb2._ANY
DESCRIPTOR.message_types_by_name['DeletedFilePB'] = _DELETEDFILEPB
DESCRIPTOR.message_types_by_name['UserBoundaryValuePB'] = _USERBOUNDARYVALUEPB
DESCRIPTOR.message_types_by_name['BoundaryValuesPB'] = _BOUNDARYVALUESPB
DESCRIPTOR.message_types_by_name['NewFilePB'] = _NEWFILEPB
DESCRIPTOR.message_types_by_name['VersionEditPB'] = _VERSIONEDITPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DeletedFilePB = _reflection.GeneratedProtocolMessageType('DeletedFilePB', (_message.Message,), {
  'DESCRIPTOR' : _DELETEDFILEPB,
  '__module__' : 'yb.rocksdb.db.version_edit_pb2'
  # @@protoc_insertion_point(class_scope:rocksdb.DeletedFilePB)
  })
_sym_db.RegisterMessage(DeletedFilePB)

UserBoundaryValuePB = _reflection.GeneratedProtocolMessageType('UserBoundaryValuePB', (_message.Message,), {
  'DESCRIPTOR' : _USERBOUNDARYVALUEPB,
  '__module__' : 'yb.rocksdb.db.version_edit_pb2'
  # @@protoc_insertion_point(class_scope:rocksdb.UserBoundaryValuePB)
  })
_sym_db.RegisterMessage(UserBoundaryValuePB)

BoundaryValuesPB = _reflection.GeneratedProtocolMessageType('BoundaryValuesPB', (_message.Message,), {
  'DESCRIPTOR' : _BOUNDARYVALUESPB,
  '__module__' : 'yb.rocksdb.db.version_edit_pb2'
  # @@protoc_insertion_point(class_scope:rocksdb.BoundaryValuesPB)
  })
_sym_db.RegisterMessage(BoundaryValuesPB)

NewFilePB = _reflection.GeneratedProtocolMessageType('NewFilePB', (_message.Message,), {
  'DESCRIPTOR' : _NEWFILEPB,
  '__module__' : 'yb.rocksdb.db.version_edit_pb2'
  # @@protoc_insertion_point(class_scope:rocksdb.NewFilePB)
  })
_sym_db.RegisterMessage(NewFilePB)

VersionEditPB = _reflection.GeneratedProtocolMessageType('VersionEditPB', (_message.Message,), {
  'DESCRIPTOR' : _VERSIONEDITPB,
  '__module__' : 'yb.rocksdb.db.version_edit_pb2'
  # @@protoc_insertion_point(class_scope:rocksdb.VersionEditPB)
  })
_sym_db.RegisterMessage(VersionEditPB)


# @@protoc_insertion_point(module_scope)
