# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yb/cdc/cdc_consumer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from yb.common import common_pb2 as yb_dot_common_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='yb/cdc/cdc_consumer.proto',
  package='yb.cdc',
  syntax='proto3',
  serialized_options=b'\n\norg.yb.cdc',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19yb/cdc/cdc_consumer.proto\x12\x06yb.cdc\x1a\x16yb/common/common.proto\"\'\n\x14ProducerTabletListPB\x12\x0f\n\x07tablets\x18\x01 \x03(\t\"\xad\x02\n\rStreamEntryPB\x12Z\n\x1c\x63onsumer_producer_tablet_map\x18\x01 \x03(\x0b\x32\x34.yb.cdc.StreamEntryPB.ConsumerProducerTabletMapEntry\x12\x19\n\x11\x63onsumer_table_id\x18\x02 \x01(\t\x12\x19\n\x11producer_table_id\x18\x03 \x01(\t\x12*\n\"same_num_producer_consumer_tablets\x18\x04 \x01(\x08\x1a^\n\x1e\x43onsumerProducerTabletMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12+\n\x05value\x18\x02 \x01(\x0b\x32\x1c.yb.cdc.ProducerTabletListPB:\x02\x38\x01\"\xfb\x01\n\x0fProducerEntryPB\x12:\n\nstream_map\x18\x01 \x03(\x0b\x32&.yb.cdc.ProducerEntryPB.StreamMapEntry\x12$\n\x0cmaster_addrs\x18\x02 \x03(\x0b\x32\x0e.yb.HostPortPB\x12%\n\rtserver_addrs\x18\x03 \x03(\x0b\x32\x0e.yb.HostPortPB\x12\x16\n\x0e\x64isable_stream\x18\x04 \x01(\x08\x1aG\n\x0eStreamMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12$\n\x05value\x18\x02 \x01(\x0b\x32\x15.yb.cdc.StreamEntryPB:\x02\x38\x01\"\xa4\x01\n\x12\x43onsumerRegistryPB\x12\x41\n\x0cproducer_map\x18\x01 \x03(\x0b\x32+.yb.cdc.ConsumerRegistryPB.ProducerMapEntry\x1aK\n\x10ProducerMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.yb.cdc.ProducerEntryPB:\x02\x38\x01\x42\x0c\n\norg.yb.cdcb\x06proto3'
  ,
  dependencies=[yb_dot_common_dot_common__pb2.DESCRIPTOR,])




_PRODUCERTABLETLISTPB = _descriptor.Descriptor(
  name='ProducerTabletListPB',
  full_name='yb.cdc.ProducerTabletListPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tablets', full_name='yb.cdc.ProducerTabletListPB.tablets', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=100,
)


_STREAMENTRYPB_CONSUMERPRODUCERTABLETMAPENTRY = _descriptor.Descriptor(
  name='ConsumerProducerTabletMapEntry',
  full_name='yb.cdc.StreamEntryPB.ConsumerProducerTabletMapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='yb.cdc.StreamEntryPB.ConsumerProducerTabletMapEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='yb.cdc.StreamEntryPB.ConsumerProducerTabletMapEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=310,
  serialized_end=404,
)

_STREAMENTRYPB = _descriptor.Descriptor(
  name='StreamEntryPB',
  full_name='yb.cdc.StreamEntryPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='consumer_producer_tablet_map', full_name='yb.cdc.StreamEntryPB.consumer_producer_tablet_map', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='consumer_table_id', full_name='yb.cdc.StreamEntryPB.consumer_table_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='producer_table_id', full_name='yb.cdc.StreamEntryPB.producer_table_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='same_num_producer_consumer_tablets', full_name='yb.cdc.StreamEntryPB.same_num_producer_consumer_tablets', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_STREAMENTRYPB_CONSUMERPRODUCERTABLETMAPENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=404,
)


_PRODUCERENTRYPB_STREAMMAPENTRY = _descriptor.Descriptor(
  name='StreamMapEntry',
  full_name='yb.cdc.ProducerEntryPB.StreamMapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='yb.cdc.ProducerEntryPB.StreamMapEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='yb.cdc.ProducerEntryPB.StreamMapEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=587,
  serialized_end=658,
)

_PRODUCERENTRYPB = _descriptor.Descriptor(
  name='ProducerEntryPB',
  full_name='yb.cdc.ProducerEntryPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='stream_map', full_name='yb.cdc.ProducerEntryPB.stream_map', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='master_addrs', full_name='yb.cdc.ProducerEntryPB.master_addrs', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tserver_addrs', full_name='yb.cdc.ProducerEntryPB.tserver_addrs', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='disable_stream', full_name='yb.cdc.ProducerEntryPB.disable_stream', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_PRODUCERENTRYPB_STREAMMAPENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=407,
  serialized_end=658,
)


_CONSUMERREGISTRYPB_PRODUCERMAPENTRY = _descriptor.Descriptor(
  name='ProducerMapEntry',
  full_name='yb.cdc.ConsumerRegistryPB.ProducerMapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='yb.cdc.ConsumerRegistryPB.ProducerMapEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='yb.cdc.ConsumerRegistryPB.ProducerMapEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=750,
  serialized_end=825,
)

_CONSUMERREGISTRYPB = _descriptor.Descriptor(
  name='ConsumerRegistryPB',
  full_name='yb.cdc.ConsumerRegistryPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='producer_map', full_name='yb.cdc.ConsumerRegistryPB.producer_map', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_CONSUMERREGISTRYPB_PRODUCERMAPENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=661,
  serialized_end=825,
)

_STREAMENTRYPB_CONSUMERPRODUCERTABLETMAPENTRY.fields_by_name['value'].message_type = _PRODUCERTABLETLISTPB
_STREAMENTRYPB_CONSUMERPRODUCERTABLETMAPENTRY.containing_type = _STREAMENTRYPB
_STREAMENTRYPB.fields_by_name['consumer_producer_tablet_map'].message_type = _STREAMENTRYPB_CONSUMERPRODUCERTABLETMAPENTRY
_PRODUCERENTRYPB_STREAMMAPENTRY.fields_by_name['value'].message_type = _STREAMENTRYPB
_PRODUCERENTRYPB_STREAMMAPENTRY.containing_type = _PRODUCERENTRYPB
_PRODUCERENTRYPB.fields_by_name['stream_map'].message_type = _PRODUCERENTRYPB_STREAMMAPENTRY
_PRODUCERENTRYPB.fields_by_name['master_addrs'].message_type = yb_dot_common_dot_common__pb2._HOSTPORTPB
_PRODUCERENTRYPB.fields_by_name['tserver_addrs'].message_type = yb_dot_common_dot_common__pb2._HOSTPORTPB
_CONSUMERREGISTRYPB_PRODUCERMAPENTRY.fields_by_name['value'].message_type = _PRODUCERENTRYPB
_CONSUMERREGISTRYPB_PRODUCERMAPENTRY.containing_type = _CONSUMERREGISTRYPB
_CONSUMERREGISTRYPB.fields_by_name['producer_map'].message_type = _CONSUMERREGISTRYPB_PRODUCERMAPENTRY
DESCRIPTOR.message_types_by_name['ProducerTabletListPB'] = _PRODUCERTABLETLISTPB
DESCRIPTOR.message_types_by_name['StreamEntryPB'] = _STREAMENTRYPB
DESCRIPTOR.message_types_by_name['ProducerEntryPB'] = _PRODUCERENTRYPB
DESCRIPTOR.message_types_by_name['ConsumerRegistryPB'] = _CONSUMERREGISTRYPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProducerTabletListPB = _reflection.GeneratedProtocolMessageType('ProducerTabletListPB', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCERTABLETLISTPB,
  '__module__' : 'yb.cdc.cdc_consumer_pb2'
  # @@protoc_insertion_point(class_scope:yb.cdc.ProducerTabletListPB)
  })
_sym_db.RegisterMessage(ProducerTabletListPB)

StreamEntryPB = _reflection.GeneratedProtocolMessageType('StreamEntryPB', (_message.Message,), {

  'ConsumerProducerTabletMapEntry' : _reflection.GeneratedProtocolMessageType('ConsumerProducerTabletMapEntry', (_message.Message,), {
    'DESCRIPTOR' : _STREAMENTRYPB_CONSUMERPRODUCERTABLETMAPENTRY,
    '__module__' : 'yb.cdc.cdc_consumer_pb2'
    # @@protoc_insertion_point(class_scope:yb.cdc.StreamEntryPB.ConsumerProducerTabletMapEntry)
    })
  ,
  'DESCRIPTOR' : _STREAMENTRYPB,
  '__module__' : 'yb.cdc.cdc_consumer_pb2'
  # @@protoc_insertion_point(class_scope:yb.cdc.StreamEntryPB)
  })
_sym_db.RegisterMessage(StreamEntryPB)
_sym_db.RegisterMessage(StreamEntryPB.ConsumerProducerTabletMapEntry)

ProducerEntryPB = _reflection.GeneratedProtocolMessageType('ProducerEntryPB', (_message.Message,), {

  'StreamMapEntry' : _reflection.GeneratedProtocolMessageType('StreamMapEntry', (_message.Message,), {
    'DESCRIPTOR' : _PRODUCERENTRYPB_STREAMMAPENTRY,
    '__module__' : 'yb.cdc.cdc_consumer_pb2'
    # @@protoc_insertion_point(class_scope:yb.cdc.ProducerEntryPB.StreamMapEntry)
    })
  ,
  'DESCRIPTOR' : _PRODUCERENTRYPB,
  '__module__' : 'yb.cdc.cdc_consumer_pb2'
  # @@protoc_insertion_point(class_scope:yb.cdc.ProducerEntryPB)
  })
_sym_db.RegisterMessage(ProducerEntryPB)
_sym_db.RegisterMessage(ProducerEntryPB.StreamMapEntry)

ConsumerRegistryPB = _reflection.GeneratedProtocolMessageType('ConsumerRegistryPB', (_message.Message,), {

  'ProducerMapEntry' : _reflection.GeneratedProtocolMessageType('ProducerMapEntry', (_message.Message,), {
    'DESCRIPTOR' : _CONSUMERREGISTRYPB_PRODUCERMAPENTRY,
    '__module__' : 'yb.cdc.cdc_consumer_pb2'
    # @@protoc_insertion_point(class_scope:yb.cdc.ConsumerRegistryPB.ProducerMapEntry)
    })
  ,
  'DESCRIPTOR' : _CONSUMERREGISTRYPB,
  '__module__' : 'yb.cdc.cdc_consumer_pb2'
  # @@protoc_insertion_point(class_scope:yb.cdc.ConsumerRegistryPB)
  })
_sym_db.RegisterMessage(ConsumerRegistryPB)
_sym_db.RegisterMessage(ConsumerRegistryPB.ProducerMapEntry)


DESCRIPTOR._options = None
_STREAMENTRYPB_CONSUMERPRODUCERTABLETMAPENTRY._options = None
_PRODUCERENTRYPB_STREAMMAPENTRY._options = None
_CONSUMERREGISTRYPB_PRODUCERMAPENTRY._options = None
# @@protoc_insertion_point(module_scope)
