# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yb/common/consensus_metadata.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from yb.common import common_pb2 as yb_dot_common_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='yb/common/consensus_metadata.proto',
  package='yb.consensus',
  syntax='proto2',
  serialized_options=b'\n\020org.yb.consensus',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\"yb/common/consensus_metadata.proto\x12\x0cyb.consensus\x1a\x16yb/common/common.proto\"\xb1\x03\n\nRaftPeerPB\x12\x16\n\x0epermanent_uuid\x18\x01 \x01(\x0c\x12\x38\n\x0bmember_type\x18\x02 \x01(\x0e\x32#.yb.consensus.RaftPeerPB.MemberType\x12/\n\x17last_known_private_addr\x18\x03 \x03(\x0b\x32\x0e.yb.HostPortPB\x12\x31\n\x19last_known_broadcast_addr\x18\x04 \x03(\x0b\x32\x0e.yb.HostPortPB\x12#\n\ncloud_info\x18\x05 \x01(\x0b\x32\x0f.yb.CloudInfoPB\"f\n\x04Role\x12\x0c\n\x08\x46OLLOWER\x10\x00\x12\n\n\x06LEADER\x10\x01\x12\x0b\n\x07LEARNER\x10\x02\x12\x13\n\x0fNON_PARTICIPANT\x10\x03\x12\x10\n\x0cREAD_REPLICA\x10\x04\x12\x10\n\x0cUNKNOWN_ROLE\x10\x07\"`\n\nMemberType\x12\x18\n\x13UNKNOWN_MEMBER_TYPE\x10\xe7\x07\x12\r\n\tPRE_VOTER\x10\x00\x12\t\n\x05VOTER\x10\x01\x12\x10\n\x0cPRE_OBSERVER\x10\x02\x12\x0c\n\x08OBSERVER\x10\x03\"K\n\x0cRaftConfigPB\x12\x12\n\nopid_index\x18\x01 \x01(\x03\x12\'\n\x05peers\x18\x02 \x03(\x0b\x32\x18.yb.consensus.RaftPeerPB\"i\n\x10\x43onsensusStatePB\x12\x14\n\x0c\x63urrent_term\x18\x01 \x02(\x03\x12\x13\n\x0bleader_uuid\x18\x02 \x01(\t\x12*\n\x06\x63onfig\x18\x03 \x02(\x0b\x32\x1a.yb.consensus.RaftConfigPB\"t\n\x13\x43onsensusMetadataPB\x12\x34\n\x10\x63ommitted_config\x18\x01 \x02(\x0b\x32\x1a.yb.consensus.RaftConfigPB\x12\x14\n\x0c\x63urrent_term\x18\x02 \x02(\x03\x12\x11\n\tvoted_for\x18\x03 \x01(\t*q\n\x13\x43onsensusConfigType\x12\x1d\n\x18\x43ONSENSUS_CONFIG_UNKNOWN\x10\xe7\x07\x12\x1e\n\x1a\x43ONSENSUS_CONFIG_COMMITTED\x10\x01\x12\x1b\n\x17\x43ONSENSUS_CONFIG_ACTIVE\x10\x02\x42\x12\n\x10org.yb.consensus'
  ,
  dependencies=[yb_dot_common_dot_common__pb2.DESCRIPTOR,])

_CONSENSUSCONFIGTYPE = _descriptor.EnumDescriptor(
  name='ConsensusConfigType',
  full_name='yb.consensus.ConsensusConfigType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CONSENSUS_CONFIG_UNKNOWN', index=0, number=999,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CONSENSUS_CONFIG_COMMITTED', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CONSENSUS_CONFIG_ACTIVE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=814,
  serialized_end=927,
)
_sym_db.RegisterEnumDescriptor(_CONSENSUSCONFIGTYPE)

ConsensusConfigType = enum_type_wrapper.EnumTypeWrapper(_CONSENSUSCONFIGTYPE)
CONSENSUS_CONFIG_UNKNOWN = 999
CONSENSUS_CONFIG_COMMITTED = 1
CONSENSUS_CONFIG_ACTIVE = 2


_RAFTPEERPB_ROLE = _descriptor.EnumDescriptor(
  name='Role',
  full_name='yb.consensus.RaftPeerPB.Role',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FOLLOWER', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LEADER', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LEARNER', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NON_PARTICIPANT', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='READ_REPLICA', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_ROLE', index=5, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=310,
  serialized_end=412,
)
_sym_db.RegisterEnumDescriptor(_RAFTPEERPB_ROLE)

_RAFTPEERPB_MEMBERTYPE = _descriptor.EnumDescriptor(
  name='MemberType',
  full_name='yb.consensus.RaftPeerPB.MemberType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_MEMBER_TYPE', index=0, number=999,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PRE_VOTER', index=1, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='VOTER', index=2, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PRE_OBSERVER', index=3, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OBSERVER', index=4, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=414,
  serialized_end=510,
)
_sym_db.RegisterEnumDescriptor(_RAFTPEERPB_MEMBERTYPE)


_RAFTPEERPB = _descriptor.Descriptor(
  name='RaftPeerPB',
  full_name='yb.consensus.RaftPeerPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='permanent_uuid', full_name='yb.consensus.RaftPeerPB.permanent_uuid', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='member_type', full_name='yb.consensus.RaftPeerPB.member_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=999,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_known_private_addr', full_name='yb.consensus.RaftPeerPB.last_known_private_addr', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_known_broadcast_addr', full_name='yb.consensus.RaftPeerPB.last_known_broadcast_addr', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cloud_info', full_name='yb.consensus.RaftPeerPB.cloud_info', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RAFTPEERPB_ROLE,
    _RAFTPEERPB_MEMBERTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=510,
)


_RAFTCONFIGPB = _descriptor.Descriptor(
  name='RaftConfigPB',
  full_name='yb.consensus.RaftConfigPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='opid_index', full_name='yb.consensus.RaftConfigPB.opid_index', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='peers', full_name='yb.consensus.RaftConfigPB.peers', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=512,
  serialized_end=587,
)


_CONSENSUSSTATEPB = _descriptor.Descriptor(
  name='ConsensusStatePB',
  full_name='yb.consensus.ConsensusStatePB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='current_term', full_name='yb.consensus.ConsensusStatePB.current_term', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='leader_uuid', full_name='yb.consensus.ConsensusStatePB.leader_uuid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='config', full_name='yb.consensus.ConsensusStatePB.config', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=589,
  serialized_end=694,
)


_CONSENSUSMETADATAPB = _descriptor.Descriptor(
  name='ConsensusMetadataPB',
  full_name='yb.consensus.ConsensusMetadataPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='committed_config', full_name='yb.consensus.ConsensusMetadataPB.committed_config', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='current_term', full_name='yb.consensus.ConsensusMetadataPB.current_term', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='voted_for', full_name='yb.consensus.ConsensusMetadataPB.voted_for', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=696,
  serialized_end=812,
)

_RAFTPEERPB.fields_by_name['member_type'].enum_type = _RAFTPEERPB_MEMBERTYPE
_RAFTPEERPB.fields_by_name['last_known_private_addr'].message_type = yb_dot_common_dot_common__pb2._HOSTPORTPB
_RAFTPEERPB.fields_by_name['last_known_broadcast_addr'].message_type = yb_dot_common_dot_common__pb2._HOSTPORTPB
_RAFTPEERPB.fields_by_name['cloud_info'].message_type = yb_dot_common_dot_common__pb2._CLOUDINFOPB
_RAFTPEERPB_ROLE.containing_type = _RAFTPEERPB
_RAFTPEERPB_MEMBERTYPE.containing_type = _RAFTPEERPB
_RAFTCONFIGPB.fields_by_name['peers'].message_type = _RAFTPEERPB
_CONSENSUSSTATEPB.fields_by_name['config'].message_type = _RAFTCONFIGPB
_CONSENSUSMETADATAPB.fields_by_name['committed_config'].message_type = _RAFTCONFIGPB
DESCRIPTOR.message_types_by_name['RaftPeerPB'] = _RAFTPEERPB
DESCRIPTOR.message_types_by_name['RaftConfigPB'] = _RAFTCONFIGPB
DESCRIPTOR.message_types_by_name['ConsensusStatePB'] = _CONSENSUSSTATEPB
DESCRIPTOR.message_types_by_name['ConsensusMetadataPB'] = _CONSENSUSMETADATAPB
DESCRIPTOR.enum_types_by_name['ConsensusConfigType'] = _CONSENSUSCONFIGTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RaftPeerPB = _reflection.GeneratedProtocolMessageType('RaftPeerPB', (_message.Message,), {
  'DESCRIPTOR' : _RAFTPEERPB,
  '__module__' : 'yb.common.consensus_metadata_pb2'
  # @@protoc_insertion_point(class_scope:yb.consensus.RaftPeerPB)
  })
_sym_db.RegisterMessage(RaftPeerPB)

RaftConfigPB = _reflection.GeneratedProtocolMessageType('RaftConfigPB', (_message.Message,), {
  'DESCRIPTOR' : _RAFTCONFIGPB,
  '__module__' : 'yb.common.consensus_metadata_pb2'
  # @@protoc_insertion_point(class_scope:yb.consensus.RaftConfigPB)
  })
_sym_db.RegisterMessage(RaftConfigPB)

ConsensusStatePB = _reflection.GeneratedProtocolMessageType('ConsensusStatePB', (_message.Message,), {
  'DESCRIPTOR' : _CONSENSUSSTATEPB,
  '__module__' : 'yb.common.consensus_metadata_pb2'
  # @@protoc_insertion_point(class_scope:yb.consensus.ConsensusStatePB)
  })
_sym_db.RegisterMessage(ConsensusStatePB)

ConsensusMetadataPB = _reflection.GeneratedProtocolMessageType('ConsensusMetadataPB', (_message.Message,), {
  'DESCRIPTOR' : _CONSENSUSMETADATAPB,
  '__module__' : 'yb.common.consensus_metadata_pb2'
  # @@protoc_insertion_point(class_scope:yb.consensus.ConsensusMetadataPB)
  })
_sym_db.RegisterMessage(ConsensusMetadataPB)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
