# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yb/tserver/backup.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from yb.common import common_pb2 as yb_dot_common_dot_common__pb2
from yb.tserver import tserver_pb2 as yb_dot_tserver_dot_tserver__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='yb/tserver/backup.proto',
  package='yb.tserver',
  syntax='proto3',
  serialized_options=b'\n\016org.yb.tserver',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17yb/tserver/backup.proto\x12\nyb.tserver\x1a\x19google/protobuf/any.proto\x1a\x16yb/common/common.proto\x1a\x18yb/tserver/tserver.proto\"\x90\x05\n\x19TabletSnapshotOpRequestPB\x12\x11\n\tdest_uuid\x18\x01 \x01(\x0c\x12\x42\n\toperation\x18\x02 \x01(\x0e\x32/.yb.tserver.TabletSnapshotOpRequestPB.Operation\x12\x13\n\x0bsnapshot_id\x18\x03 \x01(\x0c\x12\x11\n\ttablet_id\x18\x04 \x03(\x0c\x12\x1e\n\x16propagated_hybrid_time\x18\x05 \x01(\x06\x12\x1d\n\x15snapshot_dir_override\x18\x06 \x01(\t\x12\x1c\n\x14snapshot_hybrid_time\x18\x07 \x01(\x06\x12(\n\nextra_data\x18\x08 \x01(\x0b\x32\x14.google.protobuf.Any\x12\x10\n\x08imported\x18\t \x01(\x08\x12\x13\n\x0bschedule_id\x18\n \x01(\x0c\x12\x16\n\x0erestoration_id\x18\x0b \x01(\x0c\x12\x16\n\x0eschema_version\x18\x0c \x01(\r\x12\x1c\n\x06schema\x18\r \x01(\x0b\x32\x0c.yb.SchemaPB\x12 \n\x07indexes\x18\x0e \x03(\x0b\x32\x0f.yb.IndexInfoPB\x12%\n\x1dprevious_snapshot_hybrid_time\x18\x0f \x01(\x06\x12\x0c\n\x04hide\x18\x10 \x01(\x08\"\xa0\x01\n\tOperation\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x14\n\x10\x43REATE_ON_TABLET\x10\x01\x12\x15\n\x11RESTORE_ON_TABLET\x10\x02\x12\x14\n\x10\x44\x45LETE_ON_TABLET\x10\x03\x12\x14\n\x10\x43REATE_ON_MASTER\x10\x04\x12\x14\n\x10\x44\x45LETE_ON_MASTER\x10\x05\x12\x17\n\x13RESTORE_SYS_CATALOG\x10\x06\"l\n\x1aTabletSnapshotOpResponsePB\x12.\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x1f.yb.tserver.TabletServerErrorPB\x12\x1e\n\x16propagated_hybrid_time\x18\x02 \x01(\x06\x32~\n\x19TabletServerBackupService\x12\x61\n\x10TabletSnapshotOp\x12%.yb.tserver.TabletSnapshotOpRequestPB\x1a&.yb.tserver.TabletSnapshotOpResponsePBB\x10\n\x0eorg.yb.tserverb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,yb_dot_common_dot_common__pb2.DESCRIPTOR,yb_dot_tserver_dot_tserver__pb2.DESCRIPTOR,])



_TABLETSNAPSHOTOPREQUESTPB_OPERATION = _descriptor.EnumDescriptor(
  name='Operation',
  full_name='yb.tserver.TabletSnapshotOpRequestPB.Operation',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CREATE_ON_TABLET', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RESTORE_ON_TABLET', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DELETE_ON_TABLET', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CREATE_ON_MASTER', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DELETE_ON_MASTER', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RESTORE_SYS_CATALOG', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=613,
  serialized_end=773,
)
_sym_db.RegisterEnumDescriptor(_TABLETSNAPSHOTOPREQUESTPB_OPERATION)


_TABLETSNAPSHOTOPREQUESTPB = _descriptor.Descriptor(
  name='TabletSnapshotOpRequestPB',
  full_name='yb.tserver.TabletSnapshotOpRequestPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dest_uuid', full_name='yb.tserver.TabletSnapshotOpRequestPB.dest_uuid', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='operation', full_name='yb.tserver.TabletSnapshotOpRequestPB.operation', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='snapshot_id', full_name='yb.tserver.TabletSnapshotOpRequestPB.snapshot_id', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tablet_id', full_name='yb.tserver.TabletSnapshotOpRequestPB.tablet_id', index=3,
      number=4, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='propagated_hybrid_time', full_name='yb.tserver.TabletSnapshotOpRequestPB.propagated_hybrid_time', index=4,
      number=5, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='snapshot_dir_override', full_name='yb.tserver.TabletSnapshotOpRequestPB.snapshot_dir_override', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='snapshot_hybrid_time', full_name='yb.tserver.TabletSnapshotOpRequestPB.snapshot_hybrid_time', index=6,
      number=7, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='extra_data', full_name='yb.tserver.TabletSnapshotOpRequestPB.extra_data', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='imported', full_name='yb.tserver.TabletSnapshotOpRequestPB.imported', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='schedule_id', full_name='yb.tserver.TabletSnapshotOpRequestPB.schedule_id', index=9,
      number=10, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='restoration_id', full_name='yb.tserver.TabletSnapshotOpRequestPB.restoration_id', index=10,
      number=11, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='schema_version', full_name='yb.tserver.TabletSnapshotOpRequestPB.schema_version', index=11,
      number=12, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='schema', full_name='yb.tserver.TabletSnapshotOpRequestPB.schema', index=12,
      number=13, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='indexes', full_name='yb.tserver.TabletSnapshotOpRequestPB.indexes', index=13,
      number=14, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='previous_snapshot_hybrid_time', full_name='yb.tserver.TabletSnapshotOpRequestPB.previous_snapshot_hybrid_time', index=14,
      number=15, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hide', full_name='yb.tserver.TabletSnapshotOpRequestPB.hide', index=15,
      number=16, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TABLETSNAPSHOTOPREQUESTPB_OPERATION,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=773,
)


_TABLETSNAPSHOTOPRESPONSEPB = _descriptor.Descriptor(
  name='TabletSnapshotOpResponsePB',
  full_name='yb.tserver.TabletSnapshotOpResponsePB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='yb.tserver.TabletSnapshotOpResponsePB.error', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='propagated_hybrid_time', full_name='yb.tserver.TabletSnapshotOpResponsePB.propagated_hybrid_time', index=1,
      number=2, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=775,
  serialized_end=883,
)

_TABLETSNAPSHOTOPREQUESTPB.fields_by_name['operation'].enum_type = _TABLETSNAPSHOTOPREQUESTPB_OPERATION
_TABLETSNAPSHOTOPREQUESTPB.fields_by_name['extra_data'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_TABLETSNAPSHOTOPREQUESTPB.fields_by_name['schema'].message_type = yb_dot_common_dot_common__pb2._SCHEMAPB
_TABLETSNAPSHOTOPREQUESTPB.fields_by_name['indexes'].message_type = yb_dot_common_dot_common__pb2._INDEXINFOPB
_TABLETSNAPSHOTOPREQUESTPB_OPERATION.containing_type = _TABLETSNAPSHOTOPREQUESTPB
_TABLETSNAPSHOTOPRESPONSEPB.fields_by_name['error'].message_type = yb_dot_tserver_dot_tserver__pb2._TABLETSERVERERRORPB
DESCRIPTOR.message_types_by_name['TabletSnapshotOpRequestPB'] = _TABLETSNAPSHOTOPREQUESTPB
DESCRIPTOR.message_types_by_name['TabletSnapshotOpResponsePB'] = _TABLETSNAPSHOTOPRESPONSEPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TabletSnapshotOpRequestPB = _reflection.GeneratedProtocolMessageType('TabletSnapshotOpRequestPB', (_message.Message,), {
  'DESCRIPTOR' : _TABLETSNAPSHOTOPREQUESTPB,
  '__module__' : 'yb.tserver.backup_pb2'
  # @@protoc_insertion_point(class_scope:yb.tserver.TabletSnapshotOpRequestPB)
  })
_sym_db.RegisterMessage(TabletSnapshotOpRequestPB)

TabletSnapshotOpResponsePB = _reflection.GeneratedProtocolMessageType('TabletSnapshotOpResponsePB', (_message.Message,), {
  'DESCRIPTOR' : _TABLETSNAPSHOTOPRESPONSEPB,
  '__module__' : 'yb.tserver.backup_pb2'
  # @@protoc_insertion_point(class_scope:yb.tserver.TabletSnapshotOpResponsePB)
  })
_sym_db.RegisterMessage(TabletSnapshotOpResponsePB)


DESCRIPTOR._options = None

_TABLETSERVERBACKUPSERVICE = _descriptor.ServiceDescriptor(
  name='TabletServerBackupService',
  full_name='yb.tserver.TabletServerBackupService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=885,
  serialized_end=1011,
  methods=[
  _descriptor.MethodDescriptor(
    name='TabletSnapshotOp',
    full_name='yb.tserver.TabletServerBackupService.TabletSnapshotOp',
    index=0,
    containing_service=None,
    input_type=_TABLETSNAPSHOTOPREQUESTPB,
    output_type=_TABLETSNAPSHOTOPRESPONSEPB,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TABLETSERVERBACKUPSERVICE)

DESCRIPTOR.services_by_name['TabletServerBackupService'] = _TABLETSERVERBACKUPSERVICE

# @@protoc_insertion_point(module_scope)
